#!/usr/bin/env bash

set -eufo pipefail

source /etc/os-release
wget -O /efi/EFI/Linux/${GARDENLINUX_CNAME%"$GARDENLINUX_VERSION"}${1}+3.efi "https://gardenlinux-update-poc.s3.eu-central-1.amazonaws.com/${GARDENLINUX_CNAME%"$GARDENLINUX_VERSION"}${1}.uki"
