#!/usr/bin/env bash
set -Eeuo pipefail

VERSION="$(../bin/garden-version)"
gardenlinux_build_cre=${GARDENLINUX_BUILD_CRE:-"sudo podman"}

if [ "$(${gardenlinux_build_cre} image ls gardenlinux/slim --format \"{{.Repository}}:{{.Tag}}\")" == "" ]; then
	echo "WARNING: There is no gardenlinux/slim on this box. Since this is the builder script, it will pull no binary docker images from public repos."
	echo
	echo "Since gardenlinux/slim is needed for almost all images we pull debian/testing-slim and rename it to gardenlinux/slim so we avoid the Chicken-and-Egg problem temporarily"
	echo
	echo "Please run 'make slim' afterwards"
	echo
	base_container="ghcr.io/gardenlinux/gardenlinux:nightly"
	${gardenlinux_build_cre} pull "$base_container" 
	${gardenlinux_build_cre} tag  "$base_container" gardenlinux/slim
	${gardenlinux_build_cre} tag  "$base_container" gardenlinux/slim:$VERSION
	${gardenlinux_build_cre} tag  "$base_container" gardenlinux/slim:latest
else
	if [ "$(${gardenlinux_build_cre} image ls gardenlinux/slim:latest --format \"{{.ID}}\")" == \
	     "$(${gardenlinux_build_cre} image ls debian:testing-slim --format \"{{.ID}}\")" ]; then
		echo "WARNING: You are still using a debian:testing-slim as a temporary replacement of gardenlinux/slim:latest!"
		echo
		echo "Please run 'make slim' to fix"
	elif [ "$(${gardenlinux_build_cre} image ls gardenlinux/slim:$VERSION --format \"{{.ID}}\")" == \
	       "$(${gardenlinux_build_cre} image ls debian:testing-slim --format \"{{.ID}}\")" ]; then
		echo "WARNING: You are still using a debian:testing-slim as a temporary replacement of gardenlinux/slim:$VERSION!"
		echo
		echo "Please run 'make slim' to fix"
	fi
fi

