#!/usr/bin/env bash

set -euo pipefail

rootfs=$1
targetBase=$2
targetBaseDir=$(dirname "$targetBase")

kernel=$(echo ${rootfs}/boot/vmlinuz-* | tr " " '\n' | cut -d- -f 2- | sort -V | tail -1)
garden-chroot "${rootfs}" dracut -f /tmp/unified ${kernel} --uefi --kernel-cmdline "console=tty0 console=ttyS0,115200 rd.live.squashimg=squashfs.img root=live:CDLABEL=GardenlinuxISO rd.live.overlay.overlayfs rd.live.dir=live rd.live.ram"  -m "bash systemd systemd-initrd kernel-modules kernel-modules-extra terminfo dracut-systemd shutdown dmsquash-live" --reproducible

garden-chroot "${rootfs}" dracut -f /tmp/initrd ${kernel} -m "bash systemd systemd-initrd kernel-modules kernel-modules-extra terminfo dracut-systemd shutdown dmsquash-live" --reproducible

mkdir /tmp/CD_root
mkdir /tmp/CD_root/{isolinux,images,kernel,boot,boot/images,boot/syslinux,live}

mksquashfs "$rootfs" "/tmp/CD_root/live/squashfs.img" -comp lzo
cp "$rootfs/boot/"vmlinuz* "/tmp/CD_root/boot/images/vmlinuz"
mv "$rootfs/tmp/"initrd* "/tmp/CD_root/boot/images/initrd"
mv "${rootfs}/tmp/unified" bootx64.efi

#TODO: determine proper size
dd if=/dev/zero of=efiboot.img bs=512 count=131072
mkfs.msdos -F 16 -n 'EFIBOOTISO' efiboot.img
mmd -i efiboot.img ::EFI
mmd -i efiboot.img ::EFI/BOOT
mcopy -i efiboot.img bootx64.efi ::EFI/BOOT/bootx64.efi

mv efiboot.img /tmp/CD_root/isolinux/
cp /usr/lib/ISOLINUX/isolinux.bin /tmp/CD_root/isolinux/
cp /usr/lib/ISOLINUX/isohdpfx.bin /tmp/CD_root/isolinux/
cp /usr/lib/syslinux/modules/bios/ldlinux.c32 /tmp/CD_root/isolinux

cat << EOF > /tmp/CD_root/isolinux/isolinux.cfg
PATH /boot/syslinux
DEFAULT loadconfig

LABEL loadconfig
  CONFIG /boot/syslinux/syslinux.cfg
EOF

cat << EOF > /tmp/CD_root/boot/syslinux/syslinux.cfg
MENU TITLE gardenlinux
DEFAULT GardenlinuxRam

LABEL GardenlinuxRam
MENU LABEL Gardenlinux Live in RAM
LINUX /boot/images/vmlinuz console=tty0 console=ttyS0,115200 rd.live.squashimg=squashfs.img root=live:CDLABEL=GardenlinuxISO rd.live.overlay.overlayfs rd.live.dir=live rd.live.ram
INITRD /boot/images/initrd
EOF

xorriso -as mkisofs \
 -volid "GardenlinuxISO" \
 -o "${targetBase}.iso" \
 -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
 -c isolinux/boot.cat \
 -b isolinux/isolinux.bin \
 -no-emul-boot -boot-load-size 4 -boot-info-table \
 -eltorito-alt-boot \
 -e isolinux/efiboot.img \
 -no-emul-boot \
 -isohybrid-gpt-basdat \
 CD_root
