#!/usr/bin/env bash

rootfsDir=$1
targetBaseDir=$2

rc=0

echo "checking for an empty /proc"
absPath=$(readlink -f $(dirname "${BASH_SOURCE[0]}"))
rootfsDir=$(readlink -f "$rootfsDir")

#if ! check_rootdir "${rootfsDir}"; then
#	exit 1
#fi

nr=$(shopt -s nullglob dotglob; f=(${rootfsDir}/proc/*); echo ${#f[@]})

if [[ "$nr" -ne 0 ]]; then
	echo "FAIL - /proc is not empty!"
	echo "       expected: 0"
	echo "       got:      ${nr}"
	rc=1
else
	echo "OK - /proc is empty"
fi

exit $rc
