#!/usr/bin/env bash

# SAP Container Hardening 1.10.02
# TODO: rewrite

rootfsDir=$1
rc=0

# service accounts should no have shells
echo "checking service accounts for shell"
usersFile="${rootfsDir}/etc/passwd"
declare -a stringsToExclude=("sync")

output=$(awk -F: '$3 > 0 && $3 < 1000 && $7 !~ /\/nologin$/ && $7 !~ /\/false$/ { print $0 }' "${usersFile}")

for stringToExclude in ${stringsToExclude=}
do
      output=$(echo "${output}" | sed "/$stringToExclude/d")
done

if [ -z "${output}" ]
then
      echo "OK - all service accounts have no shells"
else
      echo "FAIL - there is a shell configured in the following service accounts:"
      echo "${output}"
      rc=1
fi

exit $rc

