#!/usr/bin/env bash

set -e
set -o pipefail

rc=0
rootfsDir=$1

# get all files with setgid bit set
sgidList=$(find ${rootfsDir} -type f -perm -2000 -exec stat -c "%n,%u,%g" {} \; 2> /dev/null | awk -v p=${rootfsDir%/} '{ gsub(p, "", $1); print;}' || true) 
sgidFile="${rootfsDir}/tmp/sgid.d/sgid.list"

echo "testing for sgid files"

# detect the sgid files that are not whitelisted
blacklist=$(echo "$sgidList" | awk -F, '{ print $1 }' | grep -vxf <(awk -F, '{ print $1 }' ${sgidFile}) || true) 
if [[ ! -z "${blacklist}" ]]; then
	rc=1
	echo "FAIL - sgid files are present that are not whitelisted!"
	echo "       sgid files: $(echo ${blacklist})"
fi

changed_err=""

# iterate over sgid files that don't match the whitelist (wrong uid/gid)
while read -r changed; do
	[[ -z "$changed" ]] && continue	
	changed_err="${changed_err}"$(echo "       expected: "$(grep -w ${changed%%,*} ${sgidFile}))"\n"
	changed_err="${changed_err}"$(echo "       got     : "$(echo -n "${changed%%,*},"; stat -c "%u,%g" ${rootfsDir}${changed%%,*}))
done <<< $(echo "$sgidList" | grep -vxf "${sgidFile}" | grep -vwf <(echo "${blacklist}")) 

if [[ ! -z "$changed_err" ]]; then
	rc=1
	echo "FAIL - following files do not match - file,owner,group"
	echo -e "$changed_err"
fi

if [[ "$rc" -eq 0 ]]; then 
	echo "OK - all good"
fi
exit $rc
