#!/usr/bin/env bash

set -euo pipefail

echo "testing pam tally settings"

rootfsDir=$1
thisDir=$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")
rootfsDir=$(readlink -e "$rootfsDir")

source "${thisDir}/helpers"

check_rootdir "${rootfsDir}" || exit 1
rc=0

if ! grep -qP '^auth[ \t]+required[ \t]+pam_tally2\.so[ \t]+deny=5[ \t]onerr=fail[ \t]+unlock_time=900[ \t]?$' "${rootfsDir}/etc/pam.d/common-auth"; then
	rc=1
fi
#if ! grep -qP '^auth[ \t]+required[ \t]+pam_tally2\.so[ \t]+deny=5[ \t]onerr=fail[ \t]+unlock_time=900[ \t]?$' "${rootfsDir}/etc/pam.d/common-account"; then
#	rc=1
#fi
#if ! grep -qP '^account[ \t]+required[ \t]+pam_tally2\.so[ \t]?$' "${rootfsDir}/etc/pam.d/common-auth"; then
#	rc=1
#fi
if ! grep -qP '^account[ \t]+required[ \t]+pam_tally2\.so[ \t]?$' "${rootfsDir}/etc/pam.d/common-account"; then
	rc=1	
fi

if [[ "${rc}" -eq 1 ]]; then
	echo "FAIL - pam tally settings are not correct"
	exit 1
else
	echo "OK - pam tally settings are correct"
	exit 0
fi
