#!/usr/bin/env bash 

update-kernel-cmdline

for kernel in /boot/vmlinuz-*; do 
   /usr/bin/kernel-install remove "${kernel#*-}"
   /usr/bin/kernel-install add "${kernel#*-}" "${kernel}" "/boot/initrd.img-${kernel#*-}"
done

update-syslinux
