# GL-TESTCOV-disaSTIGmedium-config-journal-permissions
# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000206-GPOS-00084/
# Override /usr/lib/tmpfiles.d/systemd.conf which sets mode 2755
z /var/log/journal 2750 root systemd-journal - -
