#!/usr/bin/env bash
set -Eeuo pipefail

dir="$(dirname "$(readlink -f "$BASH_SOURCE")")"

makeimage "$1" "$2.raw" < "$dir/fstab"
qemu-img convert -o subformat=streamOptimized -o adapter_type=lsilogic -f raw -O vmdk "$2.raw" "$2.vmdk"
make-ova --vmdk "$2.vmdk" --guest-id debian10_64Guest --template "$REPO_ROOT/templates/vmware.ovf.template"
