inputs:
  arch:
    description: 'Runner Architecture'
    required: false
    default: "amd64"
runs:
  using: composite
  steps:
    - name: install required packages
      shell: bash
      run: |
        sudo rm -rf /{usr/{local/{lib/{android,heroku},.ghcup,share/{dotnet,powershell,miniconda,swift}},share/{dotnet,miniconda,swift}},opt/{hostedtoolcache,microsoft},imagegeneration}
        sudo apt-get update
        if [ "${{ inputs.arch }}" = "amd64" ]; then
          sudo docker system prune -a -f
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends qemu-user-static
        elif [ "${{ inputs.arch }}" = "arm64" ]; then
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends podman uidmap slirp4netns dbus-user-session
          id="$(id -u)"
          sudo systemctl start user@$id
          export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$id/bus
          systemctl --user start dbus
          mkdir -p "$HOME/.config/containers"
          echo 'unqualified-search-registries = ["docker.io"]' > "$HOME/.config/containers/registries.conf"
        fi
