# overwrite with a stable gardenlinux version
ARG GL_VERSION=latest
# use platform-test-base image
FROM ghcr.io/gardenlinux/gardenlinux/platform-test-base:${GL_VERSION}

ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash

#Virtual Env Created in platform-test-base
ENV VIRTUAL_ENV="/opt/python-test-env/.venv"
ENV TOFU_HOME="/root"
ENV TOFUENV_INSTALL_DIR="${TOFU_HOME}/.tofuenv"
ENV TOFU_PROVIDERS_CUSTOM="${TOFU_HOME}/.terraform/providers/custom"
ENV PATH="${TOFUENV_INSTALL_DIR}/bin:${VIRTUAL_ENV}/bin:${PATH}"

# dependent SDKs for OpenTofu providers
RUN cd "$VIRTUAL_ENV_PARENT" && pipenv install --categories "azure-cli"

# install opentofu and dependent SDKs
RUN git clone --depth=1 https://github.com/tofuutils/tofuenv.git ${TOFUENV_INSTALL_DIR} \
    && echo 'trust-tofuenv: yes' > ${TOFUENV_INSTALL_DIR}/use-gpgv

# providers.tf contains OpenTofu version
COPY providers.tf ${TOFU_HOME}/providers.tf
# install pinned OpenTofu version
RUN cd ${TOFU_HOME} && tofuenv install latest-allowed && tofuenv list | head -1 | xargs tofuenv use

# install pinned providers (pinned in providers.tf and .terraform.lock.hcl)
COPY .terraform.lock.hcl ${TOFU_HOME}/.terraform.lock.hcl
RUN cd ${TOFU_HOME} && tofu init -upgrade && tofu providers mirror ${TOFU_HOME}/.terraform

# install providers from development forks
COPY .terraformrc ${TOFU_HOME}/.terraformrc
RUN curl -LO --create-dirs --output-dir ${TOFU_PROVIDERS_CUSTOM} https://github.com/gardenlinux/terraform-provider-azurerm/releases/download/v4.20.1-alpha1-secureboot1/terraform-provider-azurerm \
    && echo "526ae7f43ead2895b037f460f4d0e1f3b66d77f4ff436b3a5a68fad2e5cb3b30 ${TOFU_PROVIDERS_CUSTOM}/terraform-provider-azurerm" >${TOFU_PROVIDERS_CUSTOM}/checksum.txt \
    && sha256sum -c ${TOFU_PROVIDERS_CUSTOM}/checksum.txt \
    && chmod +x ${TOFU_PROVIDERS_CUSTOM}/terraform-provider-*

WORKDIR /gardenlinux/tests
