#!/usr/bin/env bash

set -eufo pipefail

arch=

while [ $# -gt 0 ]; do
	case "$1" in
		-a|--arch)
			arch="$2"
			shift 2
			;;
		*)
			break
			;;
	esac
done

if [ -z "$arch" ]; then
	case "$(uname -m)" in
		x86_64)
			arch=amd64
			;;
		aarch64|arm64)
			arch=arm64
			;;
		*)
			exit 1
			;;
	esac
fi

flavor=${1:-libc}
target_cname="container-${flavor}_bare-$arch"

./build "$target_cname"
