---
flavours:
  - architectures: [ 'amd64' ]
    platforms: [ metal ]
    extensions: [ [ ghost ] , [ chost ] , [ vhost ] ]
    modifiers: [ [ prod ] ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    extensions: []
    modifiers: []
    platforms: [ base ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ base ]
    extensions: [ [_build] ]
    modifiers: []
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ metal ]
    extensions: []
    modifiers: []
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ aws, azure, gcp, ali, openstack, vmware, kvm ]
    extensions: [ [ ghost ] , [ chost ] ]
    modifiers: [ [ prod ] ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ aws, azure, gcp, ali, openstack, vmware, kvm ]
    extensions: []
    modifiers: []
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ gcp ]
    extensions: [ [ chost ] ]
    modifiers: [ [ prod ] ]
    fails: [ unit ]
