#!/usr/bin/env bash

set -eufo pipefail

dir="$(dirname "${BASH_SOURCE[0]}")"
if [ -f "$dir/COMMIT" ]; then
    cat "$dir/COMMIT"
    exit 0
else
    if [ -z "$(git status --porcelain 2> /dev/null)" ]; then
        git rev-parse HEAD 2> /dev/null
    else
        echo local
    fi
fi
