#!/bin/sh

ramfree="$(free)"
diskfree="$(df)"

HEADERS="RAM"
CONTENT="$(echo "${ramfree}" | grep Mem  | awk '{printf("%s%.2f%%\033[0m", (($4/$2)<0.1)?"\033[31m":(($4/$2)<0.3)?"\033[33m":"\033[32m", $4/$2 * 100.0)}')"
if [ $(echo "${ramfree}" | grep Swap | awk '{printf $2; }') -gt 0 ]; then
	HEADERS="${HEADERS},Swap"
	CONTENT="${CONTENT},$(echo "${ramfree}" | grep Swap | awk '{printf("%s%.2f%%\033[0m", (($4/$2)<0.1)?"\033[31m":(($4/$2)<0.9)?"\033[33m":"\033[32m", $4/$2 * 100.0)}')"
fi
HEADERS="${HEADERS}$(echo "${diskfree}" | grep '^/dev'| awk '{printf(",%s", $6)}')"
CONTENT="${CONTENT}$(echo "${diskfree}" | grep '^/dev'| awk '{printf(",%s%.2f%%\033[0m", (($4/$2)<0.1)?"\033[31m":(($4/$2)<0.3)?"\033[33m":"\033[32m", $4/$2 * 100.0)}')"

echo " ,${HEADERS}\nFree:,${CONTENT}" | column -t -s,

