ARG base=debian:bookworm
FROM $base
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates build-essential libffi-dev libpython3-dev openssh-client python3 python3-venv uidmap

# Prepare virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install pipenv
COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock
RUN pipenv install --system --dev --verbose

RUN echo 'root:1:65535' | tee /etc/subuid /etc/subgid > /dev/null

COPY init /init
CMD /init
