# use a stable gardenlinux version
ARG GL_VERSION=1592.1
# use platform-test-base image
FROM gardenlinux/platform-test-base:${GL_VERSION}

ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash

#Virtual Env Created in platform-test-base
ENV VIRTUAL_ENV="/opt/python-test-env/.venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN : "Install Azure requirements" \
     && cd "$VIRTUAL_ENV_PARENT" && pipenv install --categories "azure-packages"
     # && apt-get update \
     # && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /gardenlinux/tests
