# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000480-GPOS-00225/
dictcheck=1
# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000078-GPOS-00046/
minlen=15
# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000480-GPOS-00225/
enforcing = 1
