#!/usr/bin/env bash
set -Eeuo pipefail
echo "	creating container image"

version="latest"
author="Garden Linux pipeline"

cat $2.tar.xz | podman --storage-driver vfs import - gardenlinux-tmp:$version
containerID=$(podman --storage-driver vfs container create gardenlinux-tmp bash)
echo "Container created: $containerID"
# Running overlayfs for overlayfs in not supported. Therefore, we
# swtich to vfs storage driver
podman --storage-driver vfs commit -q --author "$author" $containerID gardenlinux
podman --storage-driver vfs save gardenlinux:$version -o $2.container.tar.gz
