#!/usr/bin/env bash

set -euo pipefail

echo "testing default umask"

rootfsDir=$1
thisDir=$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")
rootfsDir=$(readlink -e "$rootfsDir")

#check_rootdir "${rootfsDir}" || exit 1

if grep -qP '^UMASK\s+027$' "${rootfsDir}/etc/login.defs"; then
       echo "OK - umask defaults to 027"       
       exit 0
else
	echo "FAIL - umask doesn't default to 027"
	exit 1
fi
