#!/bin/sh

ramfree="$(free)"
diskfree="$(df)"

echo "Free:  \
RAM $(echo "${ramfree}" | grep Mem  | awk '{printf("%s%.2f%%\033[0m", (($4/$2)<0.1)?"\033[31m":(($4/$2)<0.3)?"\033[33m":"\033[32m", $4/$2 * 100.0)}')  \
Swap $(echo "${ramfree}" | grep Swap | awk '{printf("%s%.2f%%\033[0m", (($4/$2)<0.1)?"\033[31m":(($4/$2)<0.9)?"\033[33m":"\033[32m", $4/$2 * 100.0)}')  \
Disk $(echo "${diskfree}" | grep '^/dev'| awk '{printf("%s %s%.2f%%\033[0m ", $6, (($4/$2)<0.1)?"\033[31m":(($4/$2)<0.3)?"\033[33m":"\033[32m", $4/$2 * 100.0)}')"
