#!/bin/bash

name="$1"
prefix="$2"
contents="$(cat)"

tmp="$(printf '%s' "$contents" | awk '/-----BEGIN CERTIFICATE REQUEST-----/' RS= )"
[ -z "$tmp" ] || printf "%s\n" "$tmp" > ${name}.csr;
tmp="$(printf '%s' "$contents" | awk '/-----BEGIN RSA PRIVATE KEY-----/' RS= )"
[ -z "$tmp" ] || printf "%s\n" "$tmp" > ${name}.key;

tmp="$(printf '%s' "$contents" | awk '/-----BEGIN CERTIFICATE-----/' RS= )"
if [ -n "$tmp" ]; then
    printf "%s\n" "$tmp" > ${name}.crt;

    serial=$(openssl x509 -noout -serial -in $1.crt | cut -d'=' -f2)
    if [ -n "$prefix" ] && [ -n "$serial" ]; then
	ln -s ${name}.crt ${prefix}-${serial}.crt
    fi
fi
