# https://www.stigviewer.com/stig/canonical_ubuntu_20.04_lts/2023-09-08/finding/V-238333
net.ipv4.tcp_syncookies = 1

# https://www.stigviewer.com/stig/canonical_ubuntu_20.04_lts/2023-09-08/finding/V-255913
kernel.dmesg_restrict = 1

# Ref: SRG-OS-000138-GPOS-00069
fs.suid_dumpable = 0
kernel.randomize_va_space = 2
