#!/usr/bin/env bash
set -e
set -x

own_dir="$(readlink -f "$(dirname "${0}")")"
repo_root="${own_dir}/.."
ci_dir="${repo_root}/bin"

source "${own_dir}/lib.sh"

install_kubectl
install_tkn

# retrieve and configure kubeconfig (sets KUBECONFIG env var)
kubecfg

# also handles default-values for env-vars
export_env

function cleanup_pipelineruns {
  echo "purging old pipelineruns"
  tkn \
    --namespace "${GARDENLINUX_TKN_WS}" \
    pipelineruns \
    delete \
    --force \
    --all \
    --keep 20
}

function create_credentials {
  ci/render_credentials.py \
    --outfile "${credentials_outfile}"

  if kubectl get secret -n "${GARDENLINUX_TKN_WS}" secrets &> /dev/null; then
    kubectl delete secret -n "${GARDENLINUX_TKN_WS}" secrets
  fi

  $(which kubectl) create secret generic secrets \
    -n "${GARDENLINUX_TKN_WS}" \
    --from-file=config.json="${credentials_outfile}"
}


echo "render pipelines"
cd "${repo_root}"

pipeline_cfg="${repo_root}/flavours.yaml"
outfile='rendered_pipeline.yaml'

if [ ! -z "${VERSION:-}" ]; then
  EXTRA_ARGS="--version=${VERSION}"
fi

cleanup_pipelineruns

head_commit="$(git rev-parse @)"
echo "head-commit: ${head_commit}"

pipeline_run="$PWD/pipeline_run.yaml"
rendered_task="$PWD/rendered_task.yaml"
credentials_outfile="$PWD/credentials.json"

# create pipeline-run for current commit
ci/render_pipeline_run.py $EXTRA_ARGS \
  --branch "${BRANCH_NAME}" \
  --committish "${head_commit}" \
  --cicd-cfg 'default' \
  --flavour-set "${FLAVOUR_SET}" \
  --git-url "${git_url}" \
  --promote-target "${PROMOTE_TARGET}" \
  --oci-path "${oci_path}" \
  --publishing-action "${PUBLISHING_ACTIONS}" \
  --outfile "${pipeline_run}"

ci/render_pipelines.py \
  --pipeline_cfg "${pipeline_cfg}" \
  --flavour-set "${FLAVOUR_SET}" \
  --outfile "${outfile}"

if [ ! -z $SECRETS_SERVER_ENDPOINT ]; then
  RENDER_TASK_EXTRA_ARGS="--use-secrets-server"
else
  # secrets-server won't be available; create config from local files and put it as
  # k8s secret into cluster.
  create_credentials
fi

ci/render_task.py \
  --outfile "${rendered_task}" \
  ${RENDER_TASK_EXTRA_ARGS}

# XXX hardcode other resources for now

for manifest in \
  "${rendered_task}" \
  "${outfile}" \
  "${pipeline_run}"
do
  $(which kubectl) apply -n "${GARDENLINUX_TKN_WS}" -f "${manifest}"
done

echo 'done: refreshed pipeline(s) and created a new pipeline-run for current commit'

echo 'will wait for new pipelinerun'
ci/wait_for_pipelinerun.py --pipelinerun-file "${pipeline_run}" --namespace "${GARDENLINUX_TKN_WS}"
