#!/usr/bin/env bash

own_dir="$(readlink -f "$(dirname "${0}")")"

source "${own_dir}/../ci/lib.sh"

install_kubectl
install_tkn

# retrieve and configure kubeconfig (sets KUBECONFIG env var)
kubecfg

export_env

echo 'retrieving release-manifests for current head'

retrieve-release-set
