# use a stable gardenlinux version
ARG GL_VERSION=1592.1
# GL_DATE=$(bin/garden-version --date ${GL_VERSION})
ARG GL_DATE=20240822
ARG GL_BASE=ghcr.io/gardenlinux/gardenlinux:${GL_VERSION}

FROM ${GL_BASE}

ARG GL_DATE
ENV DEBIAN_TESTING_VERSION=${GL_DATE}
ENV PYTHON=python3.12

ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash
ENV PYTHONPATH /gardenlinux/bin:/gardenlinux/ci:/gardenlinux/ci/glci:/gardenlinux/tests:/gardenlinux/features

COPY debian.sources /etc/apt/sources.list.d/debian.sources
COPY gardenlinux-priority /etc/apt/preferences.d/gardenlinux-priority

# use a debian testing snapshot for packages that are not in gardenlinux, yet
RUN sed -i "s/__DEBIAN_TESTING_VERSION__/${DEBIAN_TESTING_VERSION}/g" /etc/apt/sources.list.d/debian.sources \
    # keys might by expired on the snapshot repository already
    && echo "Acquire::Check-Valid-Until "0";" >/etc/apt/apt.conf.d/10no-check-valid-until \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
       ca-certificates \
       curl \
       less \
       apt-transport-https \
       gnupg \
       vim \
       procps \
       openssh-client \
       wget \
       iproute2 \
       ${PYTHON}-venv \
       lib${PYTHON}-dev \
       # qemu-img is used in some scripts
       qemu-utils \
       build-essential \
       onmetal-image \
       ### packages that are not in gardenlinux, yet
       unzip \
       inetutils-ping \
       shellcheck \
       psmisc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Prepare virtual environment
# We need a virtual env to install packages via pip, and not via apt.
# See: https://peps.python.org/pep-0668/
ENV VIRTUAL_ENV_PARENT=/opt/python-test-env
ENV VIRTUAL_ENV="$VIRTUAL_ENV_PARENT/.venv"
RUN ${PYTHON} -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY Pipfile Pipfile.lock "$VIRTUAL_ENV_PARENT/"
# Do not use --system, we want the pip from the virtual env
RUN cd "$VIRTUAL_ENV_PARENT" && pip install pipenv && pipenv install --categories "packages dev-packages"
WORKDIR /gardenlinux/tests
