[Service]
ExecStartPre=/bin/bash -c "[ -f /var/lib/kdump/initrd.img-$(uname -r) ] || ln -fs /boot/initrd.img-$(uname -r) /var/lib/kdump/initrd.img-$(uname -r); cp -u /etc/kdump/sysctl.conf /var/lib/kdump/latest_sysctls-$(uname -r)"
