#!/usr/bin/env bash

set -e

update-kernel-cmdline
update-syslinux
for kernel in /boot/vmlinuz-*; do
   kernel-install add "${kernel#*-}" "${kernel}" "/boot/initrd.img-${kernel#*-}" 2> /dev/null
done
