#!/usr/bin/env bash

set -e

update-kernel-cmdline
update-syslinux
if ls /boot/vmlinuz-* &>2 /dev/null ; then
   for kernel in /boot/vmlinuz-*; do
      kernel-install add "${kernel#*-}" "${kernel}"
   done
fi
