#!/bin/sh

set -xe

# NEEDS: awk sed tar realpath qemu-img virt-sysprep vagrant entr

TESTS_DIR="$(realpath -q ../../tests-ng)"


usage() {
    echo "$(basename $0) path/to/gardenlinux-dev-vm-image [--watch]"
    echo "--watch : rerun tests if any python file in tests-ng changes"
    echo "Note: VM image should have 'dev' feature enabled be in raw or qcow2 format"
    exit 127
}

fileext() { # file-path => file-ext
    echo "$1" | awk -F'.' '{print $NF}'
}

newext() { # file-path new-ext => file-path-with-new-ext
    echo "$1" | sed "s/\.[^.]\+$/.${2}/"
}

build_vagrant_box() { # file-path
    case $(fileext "$1") in
      raw)
        [ -f "$(newext $1 qcow2)" ] || qemu-img convert -f raw -O qcow2 "$1" "$(newext $1 qcow2)"
        image_file=$(newext "$1" qcow2)
      ;;
      qcow2)
        image_file="$1"
      ;;
      *)
        usage
      ;;
    esac

    virt-sysprep -a "$image_file" \
        --run-command 'systemctl enable ssh' \
        --ssh-inject "dev:file:${TESTS_DIR}/.ssh/id_ed25519_gl.pub"

    [ -f "$(newext `basename $1` box)" ] || ./create_box.sh "$image_file"

    vagrant box add \
        --force \
        "$(newext `basename $1` box)" \
        --name "$(newext `basename $1` gl-testing)"
    rm -f "$(newext `basename $1` box)"
}

build_test_runtime() {
    [ -f ${TESTS_DIR}/.build/runtime.tar.gz ] || ${TESTS_DIR}/util/build_runtime.sh
    mkdir -p ${TESTS_DIR}/.build/runtime
    tar xzf ${TESTS_DIR}/.build/runtime.tar.gz -C ${TESTS_DIR}/.build/runtime
}

generate_vagrantfile() { # box-name
    case $(uname -s) in
        Linux)
          libvirt_driver="kvm"
          ;;
        Darwin)
          libvirt_driver="qemu"
          ;;
        *)
          echo "*** This script only supports linux or macos as a host platform" >&2
          exit 1
          ;;
    esac
    sed -n "s/^#vagrantfile://p" "$0" \
    | sed "s/@TESTS_DIR@/${TESTS_DIR}g; s/@VAGRANT_BOX_NAME@/${1}/g; s/@LIBVIRT_DRIVER@/${libvirt_driver}/" > Vagrantfile
}

[ "$1" ] || usage
[ -f "$1" ] || usage
echo "$1" | grep -q '_dev-' || usage

vagrant box list | grep -q "$(newext `basename $1` gl-testing)" || build_vagrant_box "$1"
[ -d "${TESTS_DIR}/.build/runtime" ] || build_test_runtime
[ -s Vagrantfile ] || generate_vagrantfile "$(newext `basename $1` gl-testing)"

vagrant status | grep -q "$(newext `basename $1` gl-testing) running" || vagrant up

set +e
vagrant provision

[ "$2" = "--watch" ] && (
  find "${TESTS_DIR}" -name '*.py' | entr vagrant provision
)

#vagrantfile:Vagrant.configure("2") do |config|
#vagrantfile:  config.vm.box = "@VAGRANT_BOX_NAME@"
#vagrantfile:  config.vm.define "@VAGRANT_BOX_NAME@"
#vagrantfile:
#vagrantfile:  # https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html
#vagrantfile:  config.vm.provider :libvirt do |libvirt|
#vagrantfile:    libvirt.driver = "@LIBVIRT_DRIVER@"
#vagrantfile:    libvirt.cpu_mode = "host-passthrough"
#vagrantfile:    libvirt.default_prefix = "gardenlinux_"
#vagrantfile:    libvirt.memory   = 4096
#vagrantfile:    libvirt.cpus     = 2
#vagrantfile:    libvirt.graphics_ip = "0.0.0.0" # for vnc connection
#vagrantfile:  end
#vagrantfile:
#vagrantfile:  config.ssh.username = "dev"
#vagrantfile:  config.ssh.private_key_path = File.expand_path("@TESTS_DIR@/.ssh/id_ed25519_gl",
#vagrantfile:                                                 File.dirname(__FILE__))
#vagrantfile:
#vagrantfile:  # this mount is required by vagrant
#vagrantfile:  config.vm.synced_folder ".", "/vagrant",
#vagrantfile:    type: "nfs",
#vagrantfile:    nfs_version: 4,
#vagrantfile:    nfs_udp: false
#vagrantfile:
#vagrantfile:  config.vm.synced_folder File.expand_path("@TESTS_DIR@/.build/runtime",
#vagrantfile:                                           File.dirname(__FILE__)), "/run/gardenlinux-tests/runtime",
#vagrantfile:    type: "nfs",
#vagrantfile:    nfs_version: 4,
#vagrantfile:    nfs_udp: false
#vagrantfile:  config.vm.synced_folder File.expand_path("@TESTS_DIR@",
#vagrantfile:                                           File.dirname(__FILE__)), "/run/gardenlinux-tests/tests",
#vagrantfile:    type: "nfs",
#vagrantfile:    nfs_version: 4,
#vagrantfile:    nfs_udp: false
#vagrantfile:
#vagrantfile:  $run_tests = <<-'SCRIPT'
#vagrantfile:  set -x
#vagrantfile:  export PATH="/run/gardenlinux-tests/runtime/$(uname -m)/bin:$PATH"
#vagrantfile:
#vagrantfile:  cd /run/gardenlinux-tests/tests
#vagrantfile:  COLUMNS=120 python -m pytest -rA --tb=short --color=yes -p no:cacheprovider -s -vv \
#vagrantfile:    --system-booted --allow-system-modifications
#vagrantfile:  SCRIPT
#vagrantfile:
#vagrantfile:  config.vm.provision "shell", inline: $run_tests, upload_path: "/var/tmp/run_tests"
#vagrantfile:end
