#!/usr/bin/env bash

set -uoeE pipefail

bootDir="/boot/efi"
kernelDir="$bootDir/legacy"
configDir="/etc/kernel/cmdline.d"
configFile="/boot/efi/syslinux/syslinux.cfg"

prepare_files() {
	local v=$1
	if [ ! -d "$kernelDir/$v" ]; then 
		mkdir -p "$kernelDir/$v"
	fi
	if [ ! -f "$kernelDir/$v/linux" ]; then
		cp "/boot/vmlinuz-$v" "$kernelDir/$v/linux" && \
			chown root:root "$kernelDir/$v/linux" && \
			chmod 0644 "$kernelDir/$v/linux"
	fi
	cp -u "/boot/initrd.img-$v" "$kernelDir/$v/initrd.img-$v" && \
		chown root:root "$kernelDir/$v/initrd.img-$v" && \
		chmod 0600 "$kernelDir/$v/initrd.img-$v"
	return 0
}
# preliminary checks
#if ! mountpoint -q ${bootDir}; then
#	echo "${bootDir} is not a mountpoint" 1>&2
#	exit 1
#fi

if ! which syslinux &> /dev/null; then
	exit 0
fi

# load extra stuff
for i in "${configDir}"/*-*.cfg; do
	[ -e "$i" ] || continue
	source $i
done

versions=()
# kernel / initrd
for kernel in /boot/vmlinuz-*; do 
	if prepare_files "${kernel#*-}"; then
		versions+=("${kernel#*-}")
	fi
done

if [ "${#versions[@]}" == "0" ]; then
	echo "no valid kernels found" 1>&2
	exit 1
fi

readarray -t vSorted < <(printf '%s\n' "${versions[@]}" | sort -rV)
{
	echo "UI menu.c32"
	echo "PROMPT 0"
	echo
	echo "MENU TITLE Gardenlinux" 
	echo "TIMEOUT $TIMEOUT"
	echo "DEFAULT ${vSorted[0]}" 
	echo
	for v in "${vSorted[@]}"; do
		echo "LABEL Linux $v"
		echo " LINUX ../legacy/$v/linux"
		echo " APPEND root=${DEVICE} ${CMDLINE_LINUX}"
		echo " INITRD ../legacy/${v}/initrd.img-${v}"
		echo
	done
} > "${bootDir}/syslinux/syslinux.cfg.new" 

mv "${bootDir}/syslinux/syslinux.cfg.new" "${bootDir}/syslinux/syslinux.cfg"
