# use latest nightly by default
ARG GL_VERSION=nightly
# use platform-test-base image
FROM ghcr.io/gardenlinux/gardenlinux/platform-test-base:${GL_VERSION}

ARG TARGETARCH=amd64

ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash

#Virtual Env Created in platform-test-base
ENV VIRTUAL_ENV="/opt/python-test-env/.venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install KVM requirements based on architecture
RUN : "Install KVM requirements" \
     && apt-get update \
     && apt-get install -y --no-install-recommends \
        guestfish \
        qemu-system-x86 \
        qemu-system-arm \
        qemu-efi-aarch64 \
        # virt-copy-in command needs kernel in /boot
        linux-image-${TARGETARCH} \
        ovmf \
        # needed for OpenTofu provider dmacvicar/terraform-provider-libvirt
        # libvirt-dev \ # needed for OpenTofu provider dmacvicar/terraform-provider-libvirt
        # needed for cloud-init iso generation in OpenTofu
        # genisoimage \ # needed for cloud-init iso generation in OpenTofu
     && apt-get clean && rm -rf /var/lib/apt/lists/* \
     && cd "$VIRTUAL_ENV_PARENT" && pipenv install --categories "kvm-packages"

WORKDIR /gardenlinux/tests
