#!/bin/sh

set -e

version="$1"
bootdir=/boot

# absolute file name of kernel image may be passed as a second argument;
# create the initrd in the same directory
if [ -n "$2" ]; then
        bootdir=$(dirname "$2")
        kernel="$2"
else
        kernel="${bootdir}/vmlinuz-${version}"
fi

initrd="${bootdir}/initrd.img-${version}"


# passing the kernel version is required
[ -z "${version}" ] && exit 0

# exit if custom kernel does not need an initramfs
[ "$INITRD" = 'No' ] && initrd=''


# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
        eval set -- "$DEB_MAINT_PARAMS"
        if [ -z "$1" ] || [ "$1" != "configure" ]; then
                exit 0
        fi
fi

echo "kernel-install: installing kernel ${version}" 
/usr/bin/kernel-install remove "${version}" 
/usr/bin/kernel-install add "${version}" "${kernel}" "zzz-skip-initrd"
dracut --uefi -f "/boot/efi/Default/${kernel#*-}/linux" ${kernel#*-} --reproducible --kernel-cmdline "$(cat /etc/kernel/cmdline)"
