#!/usr/bin/env bash
set -euo pipefail

package=$(basename $0)
thisDir="$(dirname "$(readlink -f "$BASH_SOURCE")")"
source $thisDir/defaults

docker_run_patch "$package" "
	wget https://linux.mellanox.com/public/repo/bluefield/latest/extras/SOURCES/mlxbf-pka-1.0.tar.gz 
	tar zxvf mlxbf-pka-1.0.tar.gz
	pushd mlxbf-pka-1.0
	mv debian/control.no_dkms debian/control
	ls -ka /patches
	patch -p1 -i /patches/class_create.patch
	sudo apt-get build-dep -y --no-install-recommends .
	dch -i 'fix class_create for latest headers'
	dch -r ''
	WITH_DKMS=0 KVER=6.6.43-arm64 dpkg-buildpackage -b -us -uc
	sudo cp ../*.deb /packages"
