#!/usr/bin/env bash
set -euo pipefail

package=$(basename $0)
thisDir="$(dirname "$(readlink -f "$BASH_SOURCE")")"
source $thisDir/defaults

docker_run "
	wget https://linux.mellanox.com/public/repo/bluefield/latest/extras/SOURCES/mlxbf-livefish-1.0.tar.gz
	tar zxvf mlxbf-livefish-1.0.tar.gz 
	pushd mlxbf-livefish-1.0
	mv debian/control.no_dkms debian/control
	sudo apt-get build-dep -y --no-install-recommends .
	WITH_DKMS=0 KVER=6.6.43-arm64 dpkg-buildpackage -b -us -uc
	sudo cp ../*.deb /packages"
