#!/bin/bash

# List installed Garden Linux kernel headers in /usr/src/
echo "Installed Kernel Headers:"
for header in /usr/src/linux-headers-*; do
	if [ -d "$header" ]; then
		echo "$(basename $header)"
	fi
done
