#!/bin/bash

set -Eexuo pipefail

rootfs="$1"
targetBase="$2"

rootfs_work="$(mktemp -d)"
cp -a "$rootfs/." "$rootfs_work"

find "$rootfs_work/var/log/" -type f -delete

file="$(mktemp)"

size="${size:-$(du -sb "$rootfs_work" | awk '{ min_size_bytes = min_size * MB; size = $1 * 1.5; padded_size = size + (MB - (size % MB) % MB); if (padded_size < min_size_bytes) padded_size = min_size_bytes; print (padded_size / MB) "MiB" }' "MB=1048576" "min_size=64")}"
truncate -s "$size" "$file"

timestamp=$(garden-version --epoch "$version")
make_reproducible_ext4 -t "$timestamp" -h "gardenlinux:$version:firecracker:rootfs" -m -p 16 "$rootfs_work" "$file"

rm -rf "$rootfs_work"

cp "$rootfs/boot/vmlinu"*"-firecracker-${arch}" "$targetBase.vmlinux"
cp "$file" "$targetBase.ext4"

rm "$file"
