[Unit]
ConditionPathExists=|/etc/systemd/tpm2-pcr-public-key.pem
ConditionPathExists=|/run/systemd/tpm2-pcr-public-key.pem
ConditionPathExists=|/usr/local/lib/systemd/tpm2-pcr-public-key.pem
ConditionPathExists=|/usr/lib/systemd/tpm2-pcr-public-key.pem
