# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000070-GPOS-00038/
lcredit=-1
# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000071-GPOS-00039/
dcredit=-1
# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000069-GPOS-00037/
ucredit=-1
# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000266-GPOS-00101/
ocredit=-1
# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000072-GPOS-00040/
difok=8
