Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"

  # adapt to a different vagrant provider if required
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "8192"
    v.vmx["numvcpus"] = "8"
  end


  config.vm.synced_folder "../..", "/code"

  config.vm.provision "shell", inline: <<-SHELL
    cd /code/hack/local-vm-workstation/
    ./init.sh
  SHELL
end
