#!/usr/bin/env bash

set -euxo pipefail

rootfs=$1
targetBase=$2
targetBaseDir=$(dirname "$targetBase")

# extract kernel image and initramfs
cp "$rootfs/boot/"vmlinuz* "$targetBase.vmlinuz"
cp "$rootfs/boot/"initrd* "$targetBase.initrd"
chmod 644 $targetBase.initrd

# create the squashfs to include the fully generate image, excluding /boot of course as it's not needed
mksquashfs "$rootfs" "$targetBaseDir/root.squashfs" -comp lzo

(cd "$targetBaseDir"; sha256sum root.squashfs | awk '{ print $1 }' > root.squashfs.sha256sum)

(cd "$targetBaseDir"; echo -e "root.squashfs.sha256sum" | cpio -H newc -o | xz --check=crc32 >> rootfs.initrd) 
