#!/usr/bin/env bash

set -xe

makef.sh --read-only-usr --force $2 $2.tar.xz

DISK_NAME=$(dirname $2)/disk.raw
cp $2.raw ${DISK_NAME}
DIR=$(dirname $2)
GCP_TAR=$2-gcpimage.tar.gz
tar --format=oldgnu -C ${DIR} -Sczf ${GCP_TAR} $(basename ${DISK_NAME})
rm ${DISK_NAME}
