#!/usr/bin/env bash
set -Eeuo pipefail

dir="$(dirname "$(readlink -f "$BASH_SOURCE")")"

makeimage "$1" "$2.raw" < "$dir/fstab"
tar --format=oldgnu --transform "s|$2|disk|" -cSzf "$2-gcpimage.tar.gz" "$2.raw"
