#!/usr/bin/env bash
set -Eeuo pipefail

dir="$(dirname "$(readlink -f "$BASH_SOURCE")")"

makepart "$1" < "$dir/fstab" | makedisk "$1" "$2.raw"
tar --format=oldgnu --transform "s|$2|disk|" -cSzf "$2-gcpimage.tar.gz" "$2.raw"
