#!/usr/bin/env bash
set -Eeuo pipefail

ENABLE=true

# To disable immutability, create the file /etc/immutability.disabled
if [[ -f /etc/immutability.disabled ]]; then
    ENABLE=false
fi

reset-system() {
    sfdisk --delete /dev/sda 4
}

if [[ "${ENABLE}" = "true" ]]; then
    case $1 in
        halt) reset-system
        ;;
        poweroff) reset-system
        ;;
        reboot)
        ;;
        kexec)
        ;;
    esac
fi
