#!/usr/bin/env bash 

#qemu-img convert -f raw -O vmdk -o adapter_type=paraVirtual $1 $2
# default: -property vmware_disktype="sparse" \ --property vmware_adaptertype="ide" 
#qemu-img convert -o subformat=streamOptimized -f raw -O vmdk $1 $2
qemu-img convert -o subformat=streamOptimized -o adapter_type=lsilogic -f raw -O vmdk $1 $2
