#!/usr/bin/env bash

extension=${1##*.}

if [[ $extension == "vhd" ]] ; then
    extension='vpc'
fi

sudo qemu-system-x86_64 -enable-kvm -nographic -cpu host -smp 2 -m 2048 \
           -netdev user,id=eth0,hostfwd=tcp::2223-:22,hostname=debianplus \
	   -object rng-random,id=rng0,filename=/dev/random \
	   -device virtio-rng-pci,rng=rng0 \
           -device virtio-net-pci,netdev=eth0 \
	   -device virtio-scsi-pci,id=scsi0 \
	   -device scsi-hd,drive=someid,bus=scsi0.0 \
           -drive format=$extension,if=none,discard=unmap,aio=native,cache=none,id=someid,file=$1
#sudo qemu-system-x86_64 -nographic -m 2048 -netdev user,id=mynet0,net=192.168.77.0/24,dhcpstart=192.168.77.4 -drive format=raw,file=$1
#sudo qemu-system-x86_64 -nographic -m 2048 -serial stdio -netdev user,id=mynet0,net=192.168.77.0/24,dhcpstart=192.168.77.4 -drive format=raw,file=$1
#sudo qemu-system-x86_64 -m 2048 -serial stdio -drive format=raw,file=$1
