#!/usr/bin/env bash
set -euo pipefail

echo "testing for autologin setting for systemd"

rootfsDir=$1
thisDir=$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")
rootfsDir=$(readlink -e "$rootfsDir")

#check_rootdir "${rootfsDir}" || exit 1

if $(grep GARDENLINUX_FEATURES "${rootfsDir}/etc/os-release" | grep -q _dev); then
	echo "SKIP - not running when _dev feature is enabled"
	exit 0
fi

if ! output=$(grep -rE '.*/sbin/agetty.*--autologin.*' "${rootfsDir}/etc/systemd"); then
	echo "OK - no autologin settings"
	exit 0
else
	echo "FAIL - following files contain autologin settings"
	while read -r f; do
		echo ${f#"$rootfsDir"}
	done <<< "$output"
	exit 1
fi
