#!/usr/bin/env bash

set -euo pipefail

echo "testing default password hashes"

rootfsDir=$1
thisDir=$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")
rootfsDir=$(readlink -e "$rootfsDir")

source "${thisDir}/helpers"

check_rootdir "${rootfsDir}" || exit 1

if grep -qP '^password\s+\[\s?success=1\s+default=ignore\s?]\s+pam_unix\.so\s+obscure\s+use_authtok\s+try_first_pass\s+sha512\s?$' "${rootfsDir}/etc/pam.d/common-password"; then
       echo "OK - password hashes as expected"       
       exit 0
else
	echo "FAIL - password hashes do not default to sha512"
	exit 1
fi
