#!/bin/bash

rc=0

rootfsDir=$1
targetBaseDir=$2

echo "- checking for server keys"
if find $1/etc/ssh -name "ssh_host_*key"; then
	echo "  keys found!"
	rc=1
fi

echo "- checking minimum settings"


echo "- scanning user accounts"


exit $rc
