#!/usr/bin/env bash

set -euo pipefail

rootfsDir=$1
thisDir=$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")
rootfsDir=$(readlink -e "$rootfsDir")

source "${thisDir}/helpers"

check_rootdir "${rootfsDir}" || exit 1
run_in_chroot ${rootfsDir} user_groups.chroot user_groups.list

