#!/usr/bin/env bash
set -euo pipefail

own_dir="$(readlink -f "$(dirname "${0}")")"
repo_root="${own_dir}/.."

source "${own_dir}/lib.sh"

install_kubectl
install_tkn

# retrieve and configure kubeconfig (sets KUBECONFIG env var)
if [ -z ${KUBECONFIG:-} ] &&  [ -n ${SECRETS_SERVER_ENDPOINT:-} ]; then
  kubecfg
fi

whitelisted_namespaces=("concourse" "kube-system" "kube-puplic" "kube-node-lease" "tekton-pipelines" "default")

for namespace in $(kubectl get ns -ojsonpath={.items[*].metadata.name}); do

  whitelisted="false"
  for n in ${whitelisted_namespaces[*]}; do
    if [ "${namespace}" == "${n}" ]; then
      whitelisted="true"
    fi
  done
  if [ "${whitelisted}" == "true" ]; then
    echo "Namespace ${namespace} is whitelisted, skipping"
    continue
  fi

  if [ $(kubectl get pipelineruns.tekton.dev -n $namespace | wc -l) -eq 0 ]; then
    echo "No pipeline runs in namespace ${namespace}, skipping"
    continue
  fi
  if [ $(days_since_last_pipeline_run ${namespace}) -gt 20 ]; then
    echo "Found no run within the last 20 days in namespace ${namespace}, deleting"
    kubectl delete ns $namespace
  else
    echo "Found run within the last 20 days in namespace ${namespace}, will not delete"
  fi
done
