#!/usr/bin/env bash
set -euo pipefail
# set -x

own_dir="$(readlink -f "$(dirname "${0}")")"
repo_root="${own_dir}/.."

source "${own_dir}/lib.sh"

function sanitise_namespace_name {
  namespace_name=$1
  # sanitise given branch-name to k8s-namespace-name - k8s namespaces may contain only alphanumeric
  # characters and dashes. Translate everything else to a dash.
  # Note: they also must start and end with an alphanumeric character - if that isn't true for the
  # branch name, this function will fail
  echo -n ${namespace_name} | tr -c [:alnum:] -
}

function create_or_update_namespace {
  namespace_name=$1
  echo "Creating/Updating namespace with name: ${namespace_name}"

  # use kubectl to create a manifest for a namespace and apply it. Without the first step
  # kubectl would complain if the namespace already exists.
  # This will print a warning the first time this updates existing namespaces if they haven't been
  # created with 'kubectl apply'
  kubectl create ns "${namespace_name}" --dry-run=client -oyaml | kubectl apply -f -
}

function cleanup_pipelineruns {
  namespace_name=$1
  echo "purging old pipelineruns in namespace: ${namespace_name}"
  tkn \
    -n "${namespace_name}" \
    pipelineruns \
    delete \
    --force \
    --all \
    --keep 20
  echo "purging old taskruns in namespace: ${namespace_name}"
    tkn \
   -n "${namespace_name}" \
    taskruns \
    delete \
    --force \
    --all \
    --keep 50
}

function create_credentials {
  namespace_name=$1
  ci/render_credentials.py \
    --outfile "${credentials_outfile}"

  if kubectl get secret -n "${namespace_name}" secrets &> /dev/null; then
    kubectl delete secret -n "${namespace_name}" secrets
  fi

  echo "Creating secret in namespace: ${namespace_name}"
  kubectl create secret generic secrets \
    -n "${namespace_name}" \
    --from-file=config.json="${credentials_outfile}"
}

install_kubectl
install_tkn

# also handles default-values for env-vars
export_env

# retrieve and configure kubeconfig (sets KUBECONFIG env var)
if [ -z ${KUBECONFIG:-} ] &&  [ -n ${SECRETS_SERVER_ENDPOINT:-} ]; then
  kubecfg
fi

tekton_namespace="$(sanitise_namespace_name ${GARDENLINUX_TKN_WS})"
create_or_update_namespace "${tekton_namespace}"

echo "render pipelines"
cd "${repo_root}"

pipeline_cfg="${repo_root}/flavours.yaml"
outfile_pipeline_main='rendered_pipeline_main.yaml'

EXTRA_ARGS=
if [ ! -z "${VERSION:-}" ]; then
  EXTRA_ARGS="--version=${VERSION}"
fi
if [ ! -z "${ADDITIONAL_RECIPIENTS:-}" ]; then
  EXTRA_ARGS="${EXTRA_ARGS} --additional-recipients=${ADDITIONAL_RECIPIENTS}"
fi
if [ ! -z "${ONLY_RECIPIENTS:-}" ]; then
  EXTRA_ARGS="${EXTRA_ARGS} --only-recipients=${ONLY_RECIPIENTS}"
fi
if [ ! -z "${PYTEST_CFG:-}" ]; then
  EXTRA_ARGS="${EXTRA_ARGS} --pytest-cfg=${PYTEST_CFG}"
fi
if [ ! -z "${GARDENLINUX_BASE_IMAGE:-}" ]; then
  EXTRA_ARGS="${EXTRA_ARGS} --gardenlinux-base-image=${GARDENLINUX_BASE_IMAGE}"
fi

cleanup_pipelineruns "${tekton_namespace}"

if [ -z "$(git config --get pullrequest.id)" ]; then
  pr_id=""
else
  pr_id="$(git config --get pullrequest.id)"
  echo "Is a PR: ${pr_id}"
  EXTRA_ARGS="${EXTRA_ARGS} --pr-id ${pr_id}"
fi

# for local dev rendering use latest remote commit and no local one.
if [ ! -z "${CC_CONFIG_DIR:-}" ]; then
  echo "Local dev enviroment, using remote commit"
  # does not work on MacOS:
  # git ls-remote origin refs/heads/${BRANCH_NAME} | { read head_commit dummy_rest_of_line ; }
  read head_commit dummy_rest_of_line <<< $(git ls-remote origin refs/heads/${BRANCH_NAME})
else
  head_commit="$(git rev-parse @)"
fi
echo "head-commit: ${head_commit}"

pipeline_run="$PWD/pipeline_run.yaml"
rendered_task="$PWD/rendered_task.yaml"
credentials_outfile="$PWD/credentials.json"

# create pipeline-run for current commit
ci/render_pipeline_run.py $EXTRA_ARGS \
  --branch "${BRANCH_NAME}" \
  --committish "${head_commit}" \
  --cicd-cfg 'default' \
  --flavour-set "${FLAVOUR_SET}" \
  --git-url "${GIT_URL}" \
  --promote-target "${PROMOTE_TARGET}" \
  --oci-path "${OCI_PATH}" \
  --build-targets "${BUILD_TARGETS}" \
  --outfile "${pipeline_run}" \

PATCH_BRANCH=
if [ ! -z ${USE_PATCHING:-} ]; then
  export PATCH_BRANCH="${BRANCH_NAME}"
  echo "Patching target working dir with local diff against ${PATCH_BRANCH}"
fi

RENDER_TASK_EXTRA_ARGS=
if [ ! -z ${SECRETS_SERVER_ENDPOINT:-} ]; then
  RENDER_TASK_EXTRA_ARGS="--use-secrets-server"
else
  # secrets-server won't be available; create config from local files and put it as
  # k8s secret into cluster.
  echo "creating credentials in cluster"
  create_credentials "${tekton_namespace}"
fi

ci/render_all.py \
  --pipeline_cfg "${pipeline_cfg}" \
  --flavour-set "${FLAVOUR_SET}" \
  --outfile-pipeline-main "${outfile_pipeline_main}" \
  --outfile-tasks "${rendered_task}" \
  ${RENDER_TASK_EXTRA_ARGS}

# XXX hardcode other resources for now

for manifest in \
  "${rendered_task}" \
  "${outfile_pipeline_main}" \
do
  echo "Apply of ${manifest}"
  kubectl apply -n "${tekton_namespace}" -f "${manifest}"
done

image_build=false
wait=false
for arg in "$@"
do
    echo "Found arg $arg";
    if [ $arg ==  "--image-build" ]; then
      image_build=true
    fi
    if [ $arg ==  "--wait" ]; then
      wait=true
    fi
done

# --image-build calls triggering the pipeline run for image build
if [ ${image_build} = true ] ; then
  echo "Build images"
  kubectl apply -n "${tekton_namespace}" -f "${pipeline_run}"
  if [ ${wait} = true ] ; then
    echo "waiting for new pipelinerun ${pipeline_run}"
    ci/wait_for_pipelinerun.py --pipelinerun-file "${pipeline_run}" --namespace "${tekton_namespace}"
  fi
fi

echo 'done: refreshed pipeline(s) for current commit'
