#!/usr/bin/env bash
set -Eeuo pipefail

dir="$(dirname "$(readlink -f "$BASH_SOURCE")")"

# NOTE: vmdk as image format is required on the SAP CC EE
qemu-img convert -o subformat=streamOptimized -f raw -O vmdk "$1.raw" "$1.vmdk"

# NOTE: qcow2 as image format can be used on most OpenStack environments
#       (or can be easily converted back to raw format)
qemu-img convert -f raw -O qcow2 "$1.raw" "$1.qcow2"
