#!/usr/bin/env bash
set -Eeuo pipefail

dir="$(dirname "$(readlink -f "$BASH_SOURCE")")"

if [[ "$(wc -c "$1.raw" | cut -d " " -f 1)" -gt 4294967296 ]]; then
	echo "image too large"
	exit 1
fi

truncate -s 4GiB "$1.raw"

# fix GPT and image size mismatch
echo | sfdisk "$1.raw"
make-vhd -o subformat=fixed,force_size "$1.raw" "$1.vhd"
