#!/usr/bin/env bash
set -Eeuo pipefail

dir="$(dirname "$(readlink -f "$BASH_SOURCE")")"

makepart "$1" < "$dir/fstab" | makedisk "$1" "$2.raw"

if [[ "$(wc -c "$2.raw" | cut -d " " -f 1)" -gt 4294967296 ]]; then
	echo "image too large"
	exit 1
fi

truncate -s 4GiB "$2.raw"

# fix GPT and image size mismatch
echo | sfdisk "$2.raw"
make-vhd -o subformat=fixed,force_size "$2.raw" "$2.vhd"
