# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000138-GPOS-00069/
# Already available by features/server https://github.com/gardenlinux/gardenlinux/blob/4ae57fcf6251c7e95565e398f3ec7c91f76df56a/features/server/file.include/etc/sysctl.d/40-restrict-dmesg.conf
# kernel.dmesg_restrict = 1
