# https://stigaview.com/products/srg-gpos/v3r2/SRG-OS-000378-GPOS-00163/
blacklist usbcore
install usbcore /bin/true
blacklist usb-common
install usb-common /bin/true
blacklist usb-storage
install usb-storage /bin/true
