#!/bin/sh
set -e

###
### Grow root partion before anything is mounted. As nothing is mounted the
### script cannot record what it has done so it will attempt this again on 
### the next boot.
###

PREREQS=""
case $1 in
    prereqs) echo "${PREREQS}"; exit 0;;
esac

. /scripts/functions
. /scripts/local

msg() { echo "GROWROOT:" "$@" ; }
fail() { [ $# -eq 0 ] || msg "$@"; exit 1; }


local_device_setup ${ROOT} 'root file system'
rootdev="${DEV}"

case "${rootdev}" in
    *[0-9]) : ;;
    # the root is a disk, not a partition (does not end in a digit)
    # no need to do anything in this case, kernel already knows the full size.
    *) exit 0;;
esac

# remove all consective numbers from the end of rootdev to get 'rootdisk'
rootdisk=${rootdev}
while [ "${rootdisk%[0-9]}" != "${rootdisk}" ]; do
    rootdisk=${rootdisk%[0-9]};
done
partnum=${rootdev#${rootdisk}}

# account for devnameNpP devices (like mmcblk0p1).
if [ "${rootdisk%[0-9]p}" != "${rootdisk}" ] &&
    [ -b "${rootdisk%p}" ]; then
    rootdisk="${rootdisk%p}"
fi

# if the basename of the root device (ie 'xvda1' or 'sda1') exists
# in /sys/block/ then it is a block device, not a partition
# (xen xvda1 is an example of such a funny named block device)
[ -e "/sys/block/${rootdev##*/}" ] && exit 0

msg "Trying to grow partition ${rootdisk}"

# if growpart fails, exit.
# we capture stderr because on success of dry-run, it writes
# to stderr what it would do.
out=$(growpart --dry-run "${rootdisk}" "${partnum}" 2>&1) ||
    { msg "${out}"; exit 1; }

# if growpart would change something, --dry-run will write something like
#  CHANGE: partition=1 start=2048 old: size=1024000 end=1026ma048 new: size=2089192,end=2091240
# anything else, exit
case "${out}" in
    CHANGE:*) :;;
    *) exit 0;;
esac

# There was something to do, resize

# Wait for any of the initial udev events to finish
# This is to avoid any other processes using the block device that the
# root partition is on, which would cause the sfdisk 'BLKRRPART' to fail.
udevadm settle --timeout ${ROOTDELAY:-30} ||
    error "GROWROOT: WARNING: udevadm settle prior to growpart failed"

if out=$(growpart "${rootdisk}" "${partnum}" 2>&1); then
    case "$out" in
        CHANGED:*) echo "GROWROOT: $out";;
        NOCHANGE:*)
            echo "GROWROOT: WARNING: expected to grow partition, but did not";;
        *) echo "GROWROOT: unexpected output: ${out}"
    esac
else
    echo "GROWROOT: WARNING: resize failed: $out"
fi

# Wait for the partition re-read events to complete 
# so that the root partition is available when we try and mount it.
udevadm settle --timeout ${ROOTDELAY:-30}

# vi: ts=4 noexpandtab
