# use latest nightly by default
ARG GL_VERSION=nightly
# use platform-test-base image
FROM ghcr.io/gardenlinux/gardenlinux/platform-test-base:${GL_VERSION}

# optionally authenticate to github because of rate limiting
ARG GITHUB_TOKEN
ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash

COPY cloud.google.gpg /usr/share/keyrings/cloud.google.gpg

#Virtual Env Created in platform-test-base
ENV VIRTUAL_ENV="/opt/python-test-env/.venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN : "Install GCP requirements" \
     && cd "$VIRTUAL_ENV_PARENT" && pipenv install --categories "gcp-packages" \
     && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
     && apt-get update \
     && apt-get install -y google-cloud-sdk \
     && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /gardenlinux/tests
