# use latest nightly by default
ARG GL_VERSION=nightly
# use platform-test-base image
FROM ghcr.io/gardenlinux/gardenlinux/platform-test-base:${GL_VERSION}

# optionally authenticate to github because of rate limiting
ARG GITHUB_TOKEN
ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash

#Virtual Env Created in platform-test-base
ENV VIRTUAL_ENV="/opt/python-test-env/.venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN : "Install Ali requirements" \
     && cd "$VIRTUAL_ENV_PARENT" && pipenv install --categories "ali-packages" \
     && arch="$(uname -m)" \
     && [ $arch = "x86_64" ] && aliyun_arch=amd64 || aliyun_arch=arm64 \
     && [ $arch = "x86_64" ] && ossutil_arch=64 || ossutil_arch=arm64 \
     && aliyun_ver="3.0.150" \
     && ossutil_ver="1.7.6" \
     && curl -sL -o /aliyun-cli-linux-${aliyun_ver}-${aliyun_arch}.tgz https://github.com/aliyun/aliyun-cli/releases/download/v${aliyun_ver}/aliyun-cli-linux-${aliyun_ver}-${aliyun_arch}.tgz \
     && (cd /usr/local/bin ; tar xf /aliyun-cli-linux-${aliyun_ver}-${aliyun_arch}.tgz) \
     && rm /aliyun-cli-linux-${aliyun_ver}-${aliyun_arch}.tgz \
     && curl -sL -o /usr/local/bin/ossutil https://gosspublic.alicdn.com/ossutil/${ossutil_ver}/ossutil${ossutil_arch}?spm=a2c63.p38356.a3.3.44692454KkczI0  \
     && ln -s /usr/local/bin/ossutil /ossutil${ossutil_arch}?spm=a2c63.p38356.a3.3.44692454KkczI0 \
     && chmod 755 /usr/local/bin/ossutil

WORKDIR /gardenlinux/tests
