[Partition]
Type=esp
Label=ESP
MountPoint=/efi
Format=vfat
# modify the size to fit your needs
SizeMinBytes=512M
SizeMaxBytes=512M
CopyFiles=/efi
# compatibility with syslinux
FileSystemSectorSize=512
