# modify only the size to fit your needs, do not specify the size to use whatever space is left on disk
[Partition]
Type=root
Label=ROOT
MountPoint=/
Format=ext4
# do not specify the size to use whatever space is left on disk
# SizeMinBytes=2G
# SizeMaxBytes=2G
CopyFiles=/
CopyFiles=/boot
