[launcher]
launcher_version = 1

[test plan]
unit = com.canonical.certification::gardenlinux-test
forced = yes

[ui]
type = silent

[restart]
strategy = none

[transport:html_file]
type = file
path = /var/www/html/reports/index.html

[exporter:html]
unit = com.canonical.plainbox::html

[report:html]
exporter = html
transport = html_file
forced = yes
