name: build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build
  cancel-in-progress: true
on:
  workflow_call:
    inputs:
      version:
        type: string
        default: today
      use_kms:
        type: boolean
        default: false
      flavors_parse_params:
        description: 'Run bin/parse_flavors.py with these parameters'
        default: '--no-arch --json-by-arch --build --test'
        type: string
      flavors_matrix:
        type: string
    secrets:
      secureboot_db_kms_arn:
        required: false
      aws_region:
        required: false
      aws_kms_role:
        required: false
      aws_oidc_session:
        required: false
    outputs:
      flavors_matrix:
        value: ${{ jobs.flavors_matrix.outputs.matrix }}
      version:
        value: ${{ jobs.requirements.outputs.version }}
jobs:
  requirements:
    uses: ./.github/workflows/build_requirements.yml
    with:
      version: ${{ inputs.version || 'now' }}
      use_kms: ${{ github.event_name == 'workflow_dispatch' && inputs.use_kms || false }}
  bootstrap:
    needs: requirements
    uses: ./.github/workflows/build_bootstrap.yml
    with:
      version: ${{ needs.requirements.outputs.version }}
  test_containers:
    needs: requirements
    uses: ./.github/workflows/build_test_containers.yml
    with:
      version: ${{ needs.requirements.outputs.version }}
  platform_test_image:
    needs: requirements
    uses: ./.github/workflows/build_platform_test_images.yml
    with:
      version: ${{ needs.requirements.outputs.version }}
      platforms: '["tofu"]'
  flavors_matrix:
    uses: ./.github/workflows/build_flavors_matrix.yml
    with:
      flags: ${{ inputs.flavors_parse_params }}
      flavors_matrix: ${{ inputs.flavors_matrix }}
  flavors:
    needs: [ bootstrap, flavors_matrix, requirements ]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.flavors_matrix.outputs.matrix )}}
    with:
      arch: ${{ matrix.arch }}
      flavor: ${{ matrix.flavor }}
      version: ${{ needs.requirements.outputs.version }}
      # GitHub workflow workaround for bool
      use_kms: ${{ needs.requirements.outputs.use_kms == true }}
    uses: ./.github/workflows/build_flavor.yml
    secrets:
      secureboot_db_kms_arn: ${{ secrets.SECUREBOOT_DB_KMS_ARN }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_kms_role: ${{ secrets.SECUREBOOT_DB_IAM_ROLE }}
      aws_oidc_session: ${{ secrets.AWS_OIDC_SESSION }}
