name: build_requirements
on:
  workflow_call:
    inputs:
      version:
        type: string
        default: today
      use_glrd:
        type: boolean
        default: false
      target:
        type: string
        required: true
    outputs:
      commit_id:
        value: ${{ jobs.calculate_version.outputs.commit_id }}
      version:
        value: ${{ jobs.calculate_version.outputs.version }}
      signing_env:
        value: ${{ jobs.determine_environment.outputs.environment }}
      target:
        value: ${{ inputs.target }}
jobs:
  determine_environment:
    name: Determine signing environment
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-24.04
    outputs:
      environment: ${{ steps.signing_environment.outputs.environment }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0
        with:
          submodules: true
      - name: Set signing environment
        id: signing_environment
        uses: actions/github-script@v8
        with:
          script: |
            const gitHubLib = await import("${{ github.workspace }}/.github/workflows/github.mjs");
            core.setOutput("environment", gitHubLib.getGitHubSigningEnvironmentFromTarget("${{ inputs.target }}"));
  calculate_version:
    name: Build version
    defaults:
      run:
        shell: bash
    env:
      COMMIT_ID: ''
      VERSION: ''
    runs-on: ubuntu-24.04
    outputs:
      commit_id: ${{ steps.version_reference.outputs.commit_id }}
      version: ${{ steps.version_reference.outputs.version }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0
        with:
          submodules: true
      - name: Prepare build reference from GitHub
        if: ${{ inputs.version == '' || ! inputs.use_glrd }}
        id: prepare_github_reference
        run: |
          version="${{ inputs.version }}"
          if [ -z "$version" ]; then
            version="now"
          fi

          echo "COMMIT_ID=$(git rev-parse HEAD)" | tee -a "$GITHUB_ENV"
          echo "VERSION=$(./bin/garden-version "$version")" | tee -a "$GITHUB_ENV"
      - name: Prepare build reference from GLRD
        if: ${{ steps.prepare_github_reference.conclusion == 'skipped' }}
        run: |
          version=$(./bin/garden-version "${{ inputs.version }}")

          if [[ "${{ inputs.version }}" == "today" ]]; then
            glrd_data="$(./bin/glrd --type stable,patch,nightly,dev --output-format=json --latest)"
          else
            glrd_data="$(./bin/glrd --type stable,patch,nightly,dev --output-format=json --version ${{ inputs.version }})"
          fi

          commit_id=$(echo $glrd_data | jq -r '.releases[0].git.commit')
          version=$(echo $glrd_data | jq -r '(.releases[0].version.major | tostring) + "." + (.releases[0].version.minor | tostring)')

          echo "COMMIT_ID=$commit_id" | tee -a "$GITHUB_ENV"
          echo "VERSION=$version" | tee -a "$GITHUB_ENV"
      - name: Set build reference
        id: version_reference
        run: |
          echo "commit_id=$COMMIT_ID" | tee -a "$GITHUB_OUTPUT"
          echo "version=$VERSION" | tee -a "$GITHUB_OUTPUT"
  cert:
    name: Provide secure boot certificates
    needs: calculate_version
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0
        with:
          submodules: true
      - name: Set VERSION=${{ needs.calculate_version.outputs.version }}
        run: echo "${{ needs.calculate_version.outputs.version }}" | tee VERSION
      - name: Build certificates
        if: ${{ inputs.target == 'dev' }}
        run: ./cert/build
      - name: Use kms backed certificates
        if: ${{ inputs.target != 'dev' }}
        run: |
          touch cert/gardenlinux-${{ inputs.target }}-secureboot.db.arn
          for f in secureboot.{{pk,null.pk,kek,db}.{crt,der,auth},db.arn,aws-efivars} oci-sign.crt; do
            ln -sr "cert/gardenlinux-${{ inputs.target }}-$f" "cert/$f"
          done
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # pin@v4.6.2
        with:
          name: certs
          path: cert/*.*
          if-no-files-found: error
