name: Check Package Availability
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  pull_request:
    branches:
    - rel-*

permissions:
  contents: read

jobs:
  check-pkgs:
    runs-on: ubuntu-latest
    
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for missing packages in repo
        run: |
          ./bin/check-pkgs-availability.sh $PWD $(bin/garden-version)
        
