name: Check Packages
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  pull_request:
    branches:
    - rel-*

permissions:
  contents: read

jobs:
  check-pkgs:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Repository checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install requests pyyaml

      - name: Check for missing packages in repo
        run: |
          ./bin/check-pkgs-availability.py -d $(bin/garden-version)
        
      - name: Generate report
        id: generate_report
        run: |
          source venv/bin/activate
          ./bin/check-pkgs-pipelines.py
        env:
          GITLAB_PRIVATE_TOKEN: ${{ secrets.GITLAB_PRIVATE_TOKEN }}
