name: create tag
on:
  workflow_call:
    inputs:
      version:
        required: true
      type:
        required: true
jobs:
  create_tag:
  runs-on: ec2-gardenlinux-amd64
  steps:
    - uses: actions/checkout@v2
    - name: set VERSION=${{ inputs.version }}
      run: |
        bin/garden-version "${{ inputs.version }}"
        git update-index --asume-unchanged VERSION
