name: debug
on: [ push ]
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: now
  build_container:
    uses: ./.github/workflows/build-container.yml
  tests:
    needs: [ build, build_container ]
    permissions:
      id-token: write
      packages: write
    uses: ./.github/workflows/tests.yml
    secrets:
      gcp_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      gcp_project: ${{ secrets.GCP_PROJECT }}
      gcp_region: ${{ secrets.GCP_REGION }}
      gcp_zone: ${{ secrets.GCP_ZONE }}
      aws_role: ${{ secrets.AWS_TESTS_IAM_ROLE }}
      aws_session: ${{ secrets.AWS_TESTS_OIDC_SESSION }}
      aws_region: ${{ secrets.AWS_TESTS_REGION }}
