name: gcp platform tests
on:
  workflow_call:
    inputs:
      image_name:
        required: true

jobs:
  platform_test:
    environment: gcp
    env:
      gcp_project: ${{ secrets.GCP_PROJECT }}
      gcp_region: ${{ secrets.GCP_REGION }}
      gcp_zone: ${{ secrets.GCP_ZONE }}
    name: gcp platform tests
    runs-on: ec2-gardenlinux-amd64
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: 'actions/checkout@v2'
    - uses: 'actions/download-artifact@v2'
      with:
        name: ${{ inputs.image_name }}
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER}}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - name: start platform test for gcp
      run: .github/workflows/gcp_platform_tests.sh ${{ inputs.image_name }}

