name: gcp tests
on:
  workflow_call:
    secrets:
      gcp_identity_provider:
        required: true
      gcp_service_account:
        required: true
      gcp_project:
        required: true
      gcp_region:
        required: true
      gcp_zone:
        required: true
jobs:
  gcp_tests:
    name: gcp tests
    env:
      gcp_project: ${{ secrets.gcp_project }}
      gcp_region: ${{ secrets.gcp_region }}
      gcp_zone: ${{ secrets.gcp_zone }}
    runs-on: ec2-gardenlinux-${{ matrix.architecture }}
#   container: 
#     image: ghcr.io/gardenlinux/gardenlinux/integration-test:today
    permissions:
      id-token: write
      packages: write
    strategy:
      matrix:
        architecture: [ amd64 ]
        modifier: [ "" ]
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.architecture }}-gcp${{ matrix.modifier }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.gcp_identity_provider }}
          service_account: ${{ secrets.gcp_service_account }}
      
      - name: login to ghcr.io
          run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u $ --password-stdin

      - name: pull container image
          run: sudo podman pull ghcr.io/gardenlinux/gardenlinux/integration-test:today

      - name: start platform test for gcp
        run: .github/workflows/gcp_tests.sh "gcp${{ matrix.modifier }}-${{ matrix.architecture }}-*.tar.gz" 

