name: "Pull Request Labeler"
on:
  - pull_request_target

permissions: read-all # default for workflow

jobs:
  triage:
    permissions:
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # pin@v6.0.1
        with:
          dot: true
