name: build and publish images for use with lima-vm

on:
  push:
    branches:
      - lima-upload  
  schedule:
    - cron: '0 11 * * 2'
  workflow_dispatch:
    
jobs:
  build-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build image with feature:lima for amd64
      run: |
        ./build kvm-lima-amd64
        mkdir -p output
        cd ./.build
        IMAGE_AMD=$(find . -mmin -30 -maxdepth 1 -type f -name "*amd*.qcow2" -exec basename {} \;)
        cp "$IMAGE_AMD" ../output/
        sha512sum "$IMAGE_AMD" > "../output/$(basename $IMAGE_AMD).sha512"        

    - name: Dump OIDC Token claims
      run: |
        curl -s "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.googleapis.com" \
        -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq .

    - name: Authenticate to GCloud via OIDC
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.GCP_LIMA_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_LIMA_SERVICE_ACCOUNT }}'
        create_credentials_file: true
        export_environment_variables: true

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: '${{ secrets.GCP_PROJECT }}'
        install_components: 'gsutil'
          
    - name: Upload image and checksum to GCS
      run: |
        cd output
        IMAGE_AMD=$(ls *amd*.qcow2)
        SHA_AMD=$(ls *amd*.sha512)
        gsutil cp "gardenlinux.yaml" gs://${{ secrets.GCP_LIMA_BUCKET }}/gardenlinux.yaml
        gsutil cp "$IMAGE_AMD" gs://${{ secrets.GCP_LIMA_BUCKET }}/gardenlinux-amd64-today.qcow2
        gsutil cp "$SHA_AMD" gs://${{ secrets.GCP_LIMA_BUCKET }}/gardenlinux-amd64-today.qcow2.sha512

 
