name: Lima-VM Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: Garden Linux version to build, for example '1443.1' or 'main'. Use 'main' instead of 'today'.
        required: true

jobs:
  collect-metadata:
    runs-on: ubuntu-latest
    outputs:
      CNAME: ${{ steps.cname.outputs.CNAME }}
      COMMIT: ${{ steps.commit.outputs.ID }}
      VERSION: ${{ inputs.version == 'main' && 'today' ||  inputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: gardenlinux
      - uses: actions/checkout@v4
        with:
          repository: 'gardenlinux/builder'
          path: builder
      - run: sudo apt-get -y install python3 python3-mako python3-networkx python3-pefile python3-yaml
      - id: cname
        run: |
          CNAME=$(python builder/builder/parse_features --feature-dir gardenlinux/features --features kvm,lima,_curl cname_base)
          echo "CNAME=$CNAME" >> "$GITHUB_OUTPUT"
      - id: commit
        run: echo "ID=$(head -c 8 <<< $(git rev-parse HEAD 2> /dev/null))" >> "$GITHUB_OUTPUT"
        working-directory: ./gardenlinux

  build:
    runs-on: ubuntu-latest
    needs: collect-metadata
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
      # Workaround for crun version, cf https://github.com/gardenlinux/gardenlinux/pull/1982
      - uses: ./.github/actions/setup
      - name: Build the image
        run: ./build ${{ needs.collect-metadata.outputs.CNAME }}-${{ matrix.arch }}
      - name: Upload ${{ matrix.arch }} disk image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.collect-metadata.outputs.CNAME }}-${{ matrix.arch }}
          path: .build/${{ needs.collect-metadata.outputs.CNAME }}-${{ matrix.arch }}*qcow2

  lima-manifest:
    runs-on: ubuntu-latest
    needs:
      - collect-metadata
      - build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Download amd64 disk image. Requirement for later checksum creation step of generate-manifest.py
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.collect-metadata.outputs.CNAME }}-amd64
      - name: Download arm64 disk image. Requirement for later checksum creation step of generate-manifest.py
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.collect-metadata.outputs.CNAME }}-arm64
      - name: Generate lima yaml file
        run: |
          python ./features/lima/generate-manifest.py --build_dir=. --cname_base=${{ needs.collect-metadata.outputs.CNAME }} --gardenlinux_version=${{ needs.collect-metadata.outputs.VERSION }} --commit_id=${{ needs.collect-metadata.outputs.COMMIT }}
      - name: Upload lima yaml file
        uses: actions/upload-artifact@v4
        with:
          name: lima-manifest-${{ needs.collect-metadata.outputs.CNAME }}-${{ needs.collect-metadata.outputs.VERSION }}.yaml
          path: ${{ needs.collect-metadata.outputs.CNAME }}-${{ needs.collect-metadata.outputs.VERSION }}.yaml
