name: build and publish images for use with lima-vm

on:
  schedule:
    - cron: '0 11 * * 2'

jobs:
  build-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to GCloud via OIDC
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.GCP_LIMA_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_LIMA_SERVICE_ACCOUNT }}'
        create_credentials_file: true
        export_environment_variables: true

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: '${{ secrets.GCP_PROJECT }}'
        install_components: 'gsutil'

    - name: Build image with feature:lima for amd64/arm64
      run: |
        ./build kvm-lima-amd64
        ./build kvm-lima-arm64

     - name: Upload
      run: |       
        cd ./.build
        IMAGE_AMD=$(find . -mmin -20 -maxdepth 1 -type f -name "*amd*.qcow2" -exec basename {} \;)
        IMAGE_ARM=$(find . -mmin -20 -maxdepth 1 -type f -name "*arm*.qcow2" -exec basename {} \;)
        gsutil cp "${IMAGE_AMD}" gs://${{ secrets.GCP_LIMA_BUCKET }}/gardenlinux-amd64-today.qcow2
        gsutil cp "${IMAGE_ARM}" gs://${{ secrets.GCP_LIMA_BUCKET }}/gardenlinux-arm64-today.qcow2
        
    - name: Output public URL
      run: | 
        echo "amd64 image uploaded to https://images.gardenlinux.io/gardenlinux-amd64today.qcow2"
        echo "arm64 image uploaded to https://images.gardenlinux.io/gardenlinux-arm64today.qcow2"
