name: release page
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Build workflow run ID
        type: number
        required: true
      is_latest:
        default: false
        type: boolean
        description: 'Tag Github release and OCI image as latest'
      is_dev_release:
        default: false
        type: boolean
        description: 'Github development release'
      compatibility_flags:
        description: 'Flags to activate compatibility modes'
        type: string
        default: ''
env:
  GL_COMPATIBILITY_FLAGS: ${{ inputs.compatibility_flags }}
jobs:
  workflow_data:
    name: Download workflow JSON data from trigger
    uses: ./.github/workflows/download_workflow_data.yml
    with:
      run_id: ${{ inputs.run_id }}
  glrd:
    needs: workflow_data
    name: Create GLRD release
    permissions:
      id-token: write
    runs-on: ubuntu-24.04
    env:
      COMMIT: ${{ needs.workflow_data.outputs.commit_id }}
      VERSION: ${{ needs.workflow_data.outputs.version }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ needs.workflow_data.outputs.commit_id }}
          sparse-checkout: |
            flavors.yaml
          sparse-checkout-cone-mode: false
      - uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # pin@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: ${{ secrets.AWS_OIDC_SESSION }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Create GLRD release
        uses: gardenlinux/glrd@30fcac2ec9ad6cee873fcc503f0ca11022a4609e # v4.1.0
        with:
          cmd: |
            type="${{ inputs.is_dev_release && 'dev' || 'minor' }}"
            major="$(echo ${VERSION} | cut -d'.' -f1)"
            minor="$(echo ${VERSION} | cut -d'.' -f2)"

            if [ ${type} = "minor" ]; then
              # check for major version and create if missing
              if ! glrd --no-header --type major --version ${major} | grep ${major}; then
                glrd-manage --s3-update --create major --version ${major}
              fi

              glrd-manage --s3-update --create minor --version ${VERSION} --commit ${COMMIT}
            elif [ ${type} = "dev" ]; then
              glrd-manage --s3-update --create dev --version ${VERSION} --commit ${COMMIT}
            fi
      - name: Get created GLRD release
        uses: gardenlinux/glrd@30fcac2ec9ad6cee873fcc503f0ca11022a4609e # v4.1.0
        with:
          cmd: |
            glrd --type major,minor,dev --version "$(echo ${VERSION} | cut -d'.' -f1)"
  # Create new version in GLVD so it has the package list of the new release
  # This is needed for the automatic changelog generation
  glvd:
    needs: workflow_data
    if: ${{ !inputs.is_dev_release }}
    name: Update GLVD distro list
    runs-on: ubuntu-latest
    env:
      # Change this if you fork the repo
      OIDC_AUDIENCE: glvd
    permissions:
      # This is required for requesting the JWT
      id-token: write
    steps:
      - name: Authenticate to cluster
        id: kube_auth
        uses: gardener/cc-utils/.github/actions/kubernetes-auth@0c0dc641f2f7bb91345ba46d6a07779a47e43665 # 1.2755.0
        with:
          server: https://api.live.gl-live.shoot.live.k8s-hana.ondemand.com
          server-ca-discovery-url: https://discovery.ingress.garden.live.k8s.ondemand.com/projects/gl-live/shoots/3f2715e7-dc7c-4bf1-a594-dc0d90cd0f1c/cluster-ca
          audience: ${{ env.OIDC_AUDIENCE }}
      - name: Start a new ingestion job in GLVD to import package list for new version
        env:
          KUBECONFIG: kubeconfig.yaml
        run: |
          kubectl run ingest-new-gl-version-$RANDOM \
              --namespace glvd \
              --image=ghcr.io/gardenlinux/glvd-data-ingestion:latest \
              --restart=Never \
              --env=PGDATABASE=glvd \
              --env=PGUSER="${{ secrets.GLVD_DB_USERNAME }}" \
              --env=PGHOST=glvd-database-0.glvd-database \
              --env=PGPORT=5432 \
              --env=PGPASSWORD="${{ secrets.GLVD_DB_PASSWORD }}" -- /usr/local/src/ingest-single-gl-release.sh "${{ needs.workflow_data.outputs.version }}"
      - name: Wait for GLVD to ingest the package list of the new version
        run: |
          echo "Give GLVD some time to ingest the data. It is not clear how long this takes exactly, and there is no single indicator for when it was done."
          sleep 180
  github_release:
    needs: [ glvd, workflow_data ]
    if: always() && (needs.glvd.result == 'skipped' || needs.glvd.result == 'success')
    name: Generate GitHub release
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    outputs:
      id: ${{ steps.github_release.outputs.id }}
    permissions:
      id-token: write
      contents: write
      actions: write
    environment: oidc_aws_s3_upload
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ needs.workflow_data.outputs.commit_id }}
          sparse-checkout: |
            flavors.yaml
          sparse-checkout-cone-mode: false
      - name: Install python-gardenlinux-lib
        uses: gardenlinux/python-gardenlinux-lib/.github/actions/setup@3e2802f425fd877c5b632094fb6ce71f5334b567 # pin@0.10.20
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # pin@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: ${{ secrets.AWS_OIDC_SESSION }}
          aws-region: ${{ secrets.AWS_REGION }}
      - id: github_release
        name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ inputs.is_latest }}" == "true" ]]; then
            gl-gh-release create-with-gl-release-notes --tag "${{ needs.workflow_data.outputs.version }}" --commit "${{ needs.workflow_data.outputs.commit_id }}" --latest
          else
            gl-gh-release create-with-gl-release-notes --tag "${{ needs.workflow_data.outputs.version }}" --commit "${{ needs.workflow_data.outputs.commit_id }}"
          fi

          echo "id=$(cat .github_release_id)" | tee -a $GITHUB_OUTPUT
  flavors_matrix:
    needs: workflow_data
    name: Generate flavors matrix (marked for publishing)
    uses: ./.github/workflows/build_flavors_matrix.yml
    with:
      flags: "--exclude '*trustedboot*' --no-arch --json-by-arch --publish"
      ref: ${{ needs.workflow_data.outputs.commit_id }}
  github_release_artifacts_upload:
    needs: [ workflow_data, github_release, flavors_matrix ]
    if: always() && !(contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure'))
    name: Upload to existing GitHub release
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/upload_to_github_release.yml
    with:
      commit_id: ${{ needs.workflow_data.outputs.commit_id }}
      version: ${{ needs.workflow_data.outputs.version }}
      flavors_matrix: ${{ needs.flavors_matrix.outputs.matrix }}
      run_id: ${{ needs.workflow_data.outputs.run_id }}
      release_id: ${{ needs.github_release.outputs.id }}
      with_certs: false
      compatibility_flags: ${{ inputs.compatibility_flags }}
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_role: ${{ secrets.AWS_IAM_ROLE }}
      aws_session: ${{ secrets.AWS_OIDC_SESSION }}
      aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
  trustedboot_flavors_matrix:
    needs: workflow_data
    name: Generate trustedboot flavors matrix (marked for publishing)
    uses: ./.github/workflows/build_flavors_matrix.yml
    with:
      flags: "--include-only '*trustedboot*' --no-arch --json-by-arch --publish"
      ref: ${{ needs.workflow_data.outputs.commit_id }}
  github_release_trustedboot_artifacts_upload:
    needs: [ workflow_data, github_release, github_release_artifacts_upload, trustedboot_flavors_matrix ]
    if: always() && !(contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure'))
    name: Upload to existing GitHub release
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/upload_to_github_release.yml
    with:
      commit_id: ${{ needs.workflow_data.outputs.commit_id }}
      version: ${{ needs.workflow_data.outputs.version }}
      flavors_matrix: ${{ needs.trustedboot_flavors_matrix.outputs.matrix }}
      run_id: ${{ needs.workflow_data.outputs.run_id }}
      release_id: ${{ needs.github_release.outputs.id }}
      with_certs: true
      compatibility_flags: ${{ inputs.compatibility_flags }}
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_role: ${{ secrets.AWS_IAM_ROLE }}
      aws_session: ${{ secrets.AWS_OIDC_SESSION }}
      aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
  tag_container_as_latest:
    needs: workflow_data
    if: ${{ !inputs.is_dev_release }}
    name: Tag containers released
    uses: ./.github/workflows/tag_latest_container.yml
    with:
      version: ${{ needs.workflow_data.outputs.version }}
      is_latest: ${{ inputs.is_latest }}
    permissions:
      packages: write
