name: platform tests
on:
  workflow_call:
jobs:
  platform_test:
    name: platform test
    runs-on: ec2-gardenlinux-amd64
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        target: [ gcp ]
        modifier: [ "" ]
        exclude:
          - architecture: arm64
            target: gcp
        include:
          - target: gcp
            workflow_definition: ./github/workflows/gcp_platform_tests.yml

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.architecture }}-${{ matrix.target }}${{ matrix.modifier }}
      - name: Platform test for ${{ matrix.target }}
        uses: ${{ matrix.workflow_definition }}
        with: 
          image_name: build-${{ matrix.architecture }}-${{ matrix.target }}${{ matrix.modifier }}
