name: platform tests
on:
  workflow_call:
jobs:
  platform_test:
    name: platform test
    runs-on: ec2-gardenlinux-amd64
    environment: {{ $matrix.target }}
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        target: [ gcp ]
        exclude:
          - architecture: arm64
            target: gcp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.architecture }}-${{ matrix.target }}${{ matrix.modifier }}
      - uses: ./github/workflows/platform_tests/${{ matrix.target }}_platform_tests.yml
        with: 
          image_name: build-${{ matrix.architecture }}-${{ matrix.target }}${{ matrix.modifier }}
