name: platform tests
on:
  workflow_call:
jobs:
  platform_test:
    name: platform test
    runs-on: ec2-gardenlinux-amd64
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        target: [ gcp ]
        modifier: [ "" ]
        exclude:
          - architecture: arm64
            target: gcp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.architecture }}-${{ matrix.target }}${{ matrix.modifier }}
      - name: Run on azure
        if: matrix.target == 'azure'
        uses: ./github/workflows/platform_tests/aws_platform_tests.yml
        with: 
          image_name: build-${{ matrix.architecture }}-${{ matrix.target }}${{ matrix.modifier }}
      - name: Run on GCP
        if: matrix.target == 'gcp'
        uses: ./github/workflows/platform_tests/gcp_platform_tests.yml
        with: 
          image_name: build-${{ matrix.architecture }}-${{ matrix.target }}${{ matrix.modifier }}
