name: release
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        default: beta
        options:
        - beta
        - stable
      version:
        required: true
        type: string
      commit:
        required: true
        type: string
jobs:
  create_release:
    runs-on: ec2-gardenlinux-amd64
    steps:
      - uses: actions/checkout@v2
      - name: create GitHub release
        run: .github/workflows/release.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} create "${{ inputs.type == 'beta' && 'beta_' || '' }}${{ inputs.version }}" "${{ inputs.version }}" > .github_release
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: .github_release
  upload_to_release:
    needs: create_release
    permissions:
      contents: write
      id-token: write
    runs-on: ec2-gardenlinux-amd64
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        cname: [ kvm_prod, metal_prod, gcp-gardener_prod, aws-gardener_prod, azure-gardener_prod, ali-gardener_prod, openstack-gardener_prod, vmware-gardener_prod, metal_pxe_prod ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: release
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: ${{ secrets.AWS_OIDC_SESSION }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: download build artifacts from S3
        run: |
          prefix="${{ matrix.cname }}-${{ matrix.architecture }}-${{ inputs.version }}-${{ inputs.commit }}"
          .github/workflows/download_from_s3.sh "${{ secrets.AWS_S3_BUCKET }}" "$prefix"
          tar -cv "$prefix" | xz -9 > "$prefix.tar.xz"
      - name: upload to release
        run: |
          release="$(cat .github_release)"
          prefix="${{ matrix.cname }}-${{ matrix.architecture }}-${{ inputs.version }}-${{ inputs.commit }}"
          echo "$release $prefix.tar.xz"
          ls -lah "$prefix.tar.xz"
          echo "$prefix.tar.xz" | .github/workflows/release.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} upload "$release"
