name: release-test
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        default: beta
        options:
        - beta
        - stable
      version:
        required: true
        type: string
      commit:
        required: true
        type: string
        description: "Full commitish"
jobs:
  create_release:
    environment: oidc_aws_s3_upload
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt update && sudo apt install -y python3-boto3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: ${{ secrets.AWS_OIDC_SESSION }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: create GitHub release
        run: .github/workflows/release-test.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} create "${{ inputs.version }}" "${{ inputs.commit }}" "${{ inputs.version }}" > .github_release
      - name: show GitHub release
        run: cat .github_release
          