name: Check build reproducibility
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-reproducibility
  cancel-in-progress: true

# To be able to test actions on a different branch, change to workflow_dispatch after debugging is done
on:
  workflow_call:
    inputs:
      nightly:
        description: "Compared builds"
        type: string
        required: true
        default: "One new build with latest nightly"
      run_number1:
        description: "First run number (#..., only required if comparing two nightly builds)"
        type: string
      run_number2:
        description: "Second run number (#..., only required if comparing two nightly builds)"
        type: string
    secrets:
      aws_region:
        required: false
      aws_kms_role:
        required: false
      aws_oidc_session:
        required: false
      secureboot_db_kms_arn:
        required: false

jobs:
  build_a:
    name: Build A
    if: ${{ inputs.nightly != 'Two nightly builds' }}
    uses: ./.github/workflows/build.yml
    permissions:
      id-token: write
    with:
      version: now
      target: nightly
      platform_test_tag: latest
      fail_fast: true
      prefix: a-
    secrets: inherit

  run_number_a:
    uses: ./.github/workflows/get_workflow_infos.yml
    if: ${{ inputs.nightly == 'Two nightly builds' }}
    permissions:
      actions: read
    with:
      workflow_name: "nightly"
      run_number: ${{ inputs.run_number1 }}
  
  build_b:
    name: Build B
    if: ${{ inputs.nightly == 'Two new builds' }}
    uses: ./.github/workflows/build.yml
    permissions:
      id-token: write
    with:
      version: now
      target: nightly
      platform_test_tag: latest
      fail_fast: true
      prefix: b-
    secrets: inherit

  run_number_b:
    uses: ./.github/workflows/get_workflow_infos.yml
    if: ${{ inputs.nightly == 'One new build with latest nightly' || inputs.nightly == 'Two nightly builds' }}
    permissions:
      actions: read
    with:
      workflow_name: "nightly"
      run_number: ${{ inputs.nightly == 'Two nightly builds' && inputs.run_number2 || 'latest' }}

  flavors_matrix:
    name: Generate flavors matrix to build
    uses: ./.github/workflows/build_flavors_matrix.yml
    with:
      flags: '--exclude "bare-*" --no-arch --json-by-arch --build --test'

  bare_flavors_matrix:
    name: Generate bare flavors matrix to build
    uses: ./.github/workflows/build_flavors_matrix.yml
    with:
      flags: '--include-only "bare-*" --no-arch --json-by-arch --build --test'

  difference_check:
    needs: [ flavors_matrix, build_a, build_b, run_number_a, run_number_b ]
    name: Difference check
    runs-on: ubuntu-latest
    if: always()
    permissions:
      actions: read
    
    strategy:
      matrix: ${{ fromJson(needs.flavors_matrix.outputs.matrix) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
      with:
        submodules: true
    - name: Load flavor A build artifact
      if: always() && needs.build_a.result == 'success'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
      with:
        name: a-build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: A
    - name: Load flavor A build artifact from first nightly
      if: always() && needs.run_number_a.result == 'success'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
      with:
        name: build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: A
        run-id: ${{ needs.run_number_a.outputs.id }}
        github-token: ${{ github.token }}
    - name: Load flavor B build artifact
      if: always() && needs.build_b.result == 'success'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
      with:
        name: b-build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: B
    - name: Load flavor B build artifact from second nightly
      if: always() && needs.run_number_b.result == 'success'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
      with:
        name: build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: B
        run-id: ${{ needs.run_number_b.outputs.id }}
        github-token: ${{ github.token }}
    - name: Compare builds
      run: |
        cname_a=$(ls A | sed -E "s/.tar.gz$//")
        cname_b=$(ls B | sed -E "s/.tar.gz$//")

        tar -C A -xzf A/$cname_a.tar.gz
        rm "A/$cname_a.tar.gz"
        mkdir "A/unpacked"
        tar -C A/unpacked -xf A/$cname_a.tar

        tar -C B -xzf B/$cname_b.tar.gz
        rm "B/$cname_b.tar.gz"
        mkdir "B/unpacked"
        tar -C B/unpacked -xf B/$cname_b.tar

        ./.github/workflows/generate_diff.sh ${{ inputs.nightly == 'Two nightly builds' && '--nightly' || '' }} ${{ matrix.flavor }}-${{ matrix.arch }} $cname_a $cname_b
    - name: Upload diff data
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # pin@v4.6.2
      with:
        if-no-files-found: error
        name: ${{ matrix.flavor }}-${{ matrix.arch }}-diff
        path: ${{ matrix.flavor }}-${{ matrix.arch }}-diff

  bare_difference_check:
    needs: [ bare_flavors_matrix, build_a, build_b, run_number_a, run_number_b ]
    name: Difference check for bare flavors
    runs-on: ubuntu-latest
    if: always()
    permissions:
      actions: read
    
    strategy:
      matrix: ${{ fromJson(needs.bare_flavors_matrix.outputs.matrix) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
      with:
        submodules: true
    - name: Load flavor A build artifact
      if: always() && needs.build_a.result == 'success'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
      with:
        name: a-build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: A
    - name: Load flavor A build artifact from first nightly
      if: always() && needs.run_number_a.result == 'success'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
      with:
        name: build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: A
        run-id: ${{ needs.run_number_a.outputs.id }}
        github-token: ${{ github.token }}
    - name: Load flavor B build artifact
      if: always() && needs.build_b.result == 'success'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
      with:
        name: b-build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: B
    - name: Load flavor B build artifact from second nightly
      if: always() && needs.run_number_b.result == 'success'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
      with:
        name: build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: B
        run-id: ${{ needs.run_number_b.outputs.id }}
        github-token: ${{ github.token }}
    - name: Compare builds
      run: |
        podman unshare /bin/bash -c '\
        FILENAME=$(echo "${{ matrix.flavor }}-${{ matrix.arch }}.oci" | sed -E "s/bare-//");\

        a_sha=$(podman load -qi A/$FILENAME 2>/dev/null | awk '\''{ print $NF }'\'');\
        a_mount=$(podman image mount "$a_sha");\

        b_sha=$(podman load -qi B/$FILENAME 2>/dev/null | awk '\''{ print $NF }'\'');\
        b_mount=$(podman image mount "$b_sha");\

        depth=$(echo "$a_mount" | tr -cd '\''/'\'' | wc -c);\
        depth=$(($depth + 1))

        ./.github/workflows/generate_diff.sh --oci ${{ inputs.nightly == 'Two nightly builds' && '--nightly' || '' }} ${{ matrix.flavor }}-${{ matrix.arch }} "$a_mount" "$b_mount" "$depth"'
    - name: Upload diff data
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # pin@v4.6.2
      with:
        if-no-files-found: error
        name: ${{ matrix.flavor }}-${{ matrix.arch }}-diff
        path: ${{ matrix.flavor }}-${{ matrix.arch }}-diff
  
  format_result:
    needs: [ difference_check, bare_difference_check, run_number_a, run_number_b ]
    if: always()
    name: Format result
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
      with:
        submodules: true
    - name: download result data
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
      with:
        pattern: "*-diff"
        path: diffs/
        merge-multiple: true
    - name: Compare commit hashes if two nightly builds were used
      if: always() && needs.run_number_a.result == 'success' && needs.run_number_b.result == 'success'
      run: |
        run_number_a=$(echo "${{ needs.run_number_a.outputs.run_number }}" | sed -E "s/^#//")
        run_number_b=$(echo "${{ needs.run_number_a.outputs.run_number }}" | sed -E "s/^#//")
        echo -e "$run_number_a,${{ needs.run_number_a.outputs.id }},${{ needs.run_number_a.outputs.commit }};\
        $run_number_b,${{ needs.run_number_b.outputs.id }},${{ needs.run_number_b.outputs.commit }}"\
        > nightly_stats
    - name: Compare commit hashes if one nightly build was used
      if: always() && needs.build_a.result == 'success' && needs.run_number_b.result == 'success'
      run: |
        run_number_b=$(echo "${{ needs.run_number_a.outputs.run_number }}" | sed -E "s/^#//")
        echo -e ",,${{ github.sha }};\
        $run_number_b,${{ needs.run_number_b.outputs.id }},${{ needs.run_number_b.outputs.commit }}"\
        > nightly_stats
    - name: generate Result.md
      run: |
        ./.github/workflows/format_diff.py

        cat Result.md >> $GITHUB_STEP_SUMMARY
