name: Check build reproducibility
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-reproducibility
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      nightly:
        description: "Compared builds"
        type: choice
        required: true
        default: "One new build with latest nightly"
        options: 
        - "Two new builds"
        - "One new build with latest nightly"
        - "Two nightly builds"
      run_number1:
        description: "First run number (#..., only required if comparing two nightly builds)"
        type: string
      run_number2:
        description: "Second run number (#..., only required if comparing two nightly builds)"
        type: string

jobs:
  build_a:
    name: Build A
    if: ${{ inputs.nightly != 'Two nightly builds' }}
    uses: ./.github/workflows/build.yml
    permissions:
      id-token: write
      actions: write
      packages: write
    with:
      version: now
      target: nightly
      fail_fast: true
      prefix: a-
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_kms_role: ${{ secrets.KMS_SIGNING_IAM_ROLE }}
      aws_oidc_session: ${{ secrets.AWS_OIDC_SESSION }}
      secureboot_db_kms_arn: ${{ secrets.SECUREBOOT_DB_KMS_ARN }}

  run_number_a:
    uses: ./.github/workflows/get_workflow_infos.yml
    if: ${{ inputs.nightly == 'Two nightly builds' }}
    permissions:
      actions: read
    with:
      workflow_name: "nightly"
      run_number: ${{ inputs.run_number1 }}
  
  build_b:
    name: Build B
    if: ${{ inputs.nightly == 'Two new builds' }}
    uses: ./.github/workflows/build.yml
    permissions:
      id-token: write
      actions: write
      packages: write
    with:
      version: now
      target: nightly
      fail_fast: true
      prefix: b-
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_kms_role: ${{ secrets.KMS_SIGNING_IAM_ROLE }}
      aws_oidc_session: ${{ secrets.AWS_OIDC_SESSION }}
      secureboot_db_kms_arn: ${{ secrets.SECUREBOOT_DB_KMS_ARN }}

  run_number_b:
    uses: ./.github/workflows/get_workflow_infos.yml
    if: ${{ inputs.nightly == 'One new build with latest nightly' || inputs.nightly == 'Two nightly builds' }}
    permissions:
      actions: read
    with:
      workflow_name: "nightly"
      run_number: ${{ inputs.nightly == 'Two nightly builds' && inputs.run_number2 || 'latest' }}

  flavors_matrix:
    name: Generate flavors matrix to build
    uses: ./.github/workflows/build_flavors_matrix.yml
    with:
      flags: '--exclude "bare-*" --no-arch --json-by-arch --build --test'

  bare_flavors_matrix:
    name: Generate bare flavors matrix to build
    uses: ./.github/workflows/build_flavors_matrix.yml
    with:
      flags: '--include-only "bare-*" --no-arch --json-by-arch --build --test'

  difference_check:
    needs: [ flavors_matrix, build_a, build_b, run_number_a, run_number_b ]
    name: Difference check
    runs-on: ubuntu-latest
    if: always()
    permissions:
      actions: read
    
    strategy:
      matrix: ${{ fromJson(needs.flavors_matrix.outputs.matrix) }}
      fail-fast: false
    steps:
    - name: Install python-gardenlinux-lib
      uses: gardenlinux/python-gardenlinux-lib/.github/actions/setup@main
      with:
        version: "feat/port-difference-formatter"
    - name: Load flavor A build artifact
      if: always() && needs.build_a.result == 'success'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # pin@v7.0.0
      with:
        name: a-build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: A
    - name: Load flavor A build artifact from first nightly
      if: always() && needs.run_number_a.result == 'success'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # pin@v7.0.0
      with:
        name: build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: A
        run-id: ${{ needs.run_number_a.outputs.id }}
        github-token: ${{ github.token }}
    - name: Load flavor B build artifact
      if: always() && needs.build_b.result == 'success'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # pin@v7.0.0
      with:
        name: b-build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: B
    - name: Load flavor B build artifact from second nightly
      if: always() && needs.run_number_b.result == 'success'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # pin@v7.0.0
      with:
        name: build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: B
        run-id: ${{ needs.run_number_b.outputs.id }}
        github-token: ${{ github.token }}
    - name: Compare builds
      run: |
        cname_a=$(ls A | sed -E "s/.tar.gz$//")
        cname_b=$(ls B | sed -E "s/.tar.gz$//")

        tar -C A -xzf A/$cname_a.tar.gz
        rm "A/$cname_a.tar.gz"

        tar -C B -xzf B/$cname_b.tar.gz
        rm "B/$cname_b.tar.gz"

        out=$(sudo gl-diff generate ${{ inputs.nightly == 'Two nightly builds' && '--nightly' || '' }} A/$cname_a.tar B/$cname_b.tar)

        # Only create file on success or controlled failure (exit code 64)
        if [[ "$?" == 0 || "$?" == 64 ]]; then 
          echo "$out" > ${{ matrix.flavor }}-${{ matrix.arch }}-diff.txt
        fi
    - name: Upload diff data
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # pin@v6.0.0
      with:
        if-no-files-found: error
        name: ${{ matrix.flavor }}-${{ matrix.arch }}-diff.txt
        path: ${{ matrix.flavor }}-${{ matrix.arch }}-diff.txt

  bare_difference_check:
    needs: [ bare_flavors_matrix, build_a, build_b, run_number_a, run_number_b ]
    name: Difference check for bare flavors
    runs-on: ubuntu-latest
    if: always()
    permissions:
      actions: read
    
    strategy:
      matrix: ${{ fromJson(needs.bare_flavors_matrix.outputs.matrix) }}
      fail-fast: false
    steps:
    - name: Install python-gardenlinux-lib
      uses: gardenlinux/python-gardenlinux-lib/.github/actions/setup@main
      with:
        version: "feat/port-difference-formatter"
    - name: Load flavor A build artifact
      if: always() && needs.build_a.result == 'success'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # pin@v7.0.0
      with:
        name: a-build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: A
    - name: Load flavor A build artifact from first nightly
      if: always() && needs.run_number_a.result == 'success'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # pin@v7.0.0
      with:
        name: build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: A
        run-id: ${{ needs.run_number_a.outputs.id }}
        github-token: ${{ github.token }}
    - name: Load flavor B build artifact
      if: always() && needs.build_b.result == 'success'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # pin@v7.0.0
      with:
        name: b-build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: B
    - name: Load flavor B build artifact from second nightly
      if: always() && needs.run_number_b.result == 'success'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # pin@v7.0.0
      with:
        name: build-${{ matrix.flavor }}-${{ matrix.arch }}
        path: B
        run-id: ${{ needs.run_number_b.outputs.id }}
        github-token: ${{ github.token }}
    - name: Compare builds
      run: |
        filename=$(echo "${{ matrix.flavor }}-${{ matrix.arch }}.oci" | sed -E "s/bare-//")

        out=$(sudo gl-diff generate ${{ inputs.nightly == 'Two nightly builds' && '--nightly' || '' }} "A/$filename" "B/$filename")
        
        # Only create file on success or controlled failure (exit code 64)
        if [[ "$?" == 0 || "$?" == 64 ]]; then 
          echo "$out" > ${{ matrix.flavor }}-${{ matrix.arch }}-diff.txt
        fi
    - name: Upload diff data
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # pin@v6.0.0
      with:
        if-no-files-found: error
        name: ${{ matrix.flavor }}-${{ matrix.arch }}-diff.txt
        path: ${{ matrix.flavor }}-${{ matrix.arch }}-diff.txt
  
  format_result:
    needs: [ difference_check, bare_difference_check, run_number_a, run_number_b, flavors_matrix, bare_flavors_matrix ]
    if: always()
    name: Format result
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2
      with:
        submodules: true
    - name: Install python-gardenlinux-lib
      uses: gardenlinux/python-gardenlinux-lib/.github/actions/setup@main
      with:
        version: "feat/port-difference-formatter"
    - name: download result data
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # pin@v7.0.0
      with:
        pattern: "*-diff.txt"
        path: diffs/
        merge-multiple: true
    - name: Compare commit hashes if two nightly builds were used
      if: always() && needs.run_number_a.result == 'success' && needs.run_number_b.result == 'success'
      run: |
        run_number_a=$(echo "${{ needs.run_number_a.outputs.run_number }}" | sed -E "s/^#//")
        run_number_b=$(echo "${{ needs.run_number_b.outputs.run_number }}" | sed -E "s/^#//")
        echo -e "$run_number_a,${{ needs.run_number_a.outputs.id }},${{ needs.run_number_a.outputs.commit }}
        $run_number_b,${{ needs.run_number_b.outputs.id }},${{ needs.run_number_b.outputs.commit }}"\
        > nightly_stats.csv
    - name: Compare commit hashes if one nightly build was used
      if: always() && needs.run_number_a.result == 'skipped' && needs.run_number_b.result == 'success'
      run: |
        run_number_b=$(echo "${{ needs.run_number_b.outputs.run_number }}" | sed -E "s/^#//")
        echo -e ",,${{ github.sha }}
        $run_number_b,${{ needs.run_number_b.outputs.id }},${{ needs.run_number_b.outputs.commit }}"\
        > nightly_stats.csv
    - name: generate Result.md
      run: |
        gl-diff format '${{ needs.flavors_matrix.outputs.matrix }}' '${{ needs.bare_flavors_matrix.outputs.matrix }}' >> $GITHUB_STEP_SUMMARY
