name: STIG compliance

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        platform: [ kvm, aws, azure, ali, gcp, metal ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
        with:
          submodules: true
      - name: Build the image
        run: ./build ${{ matrix.platform}}-stig
      - name: Upload build logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # pin@v4.6.2
        with:
          name: STIG-${{ matrix.platform}}-logs
          path: .build/*log
          include-hidden-files: true
