name: STIG compliance

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        platform: [ kvm, aws, azure, ali, gcp, metal ]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Build the image
        run: ./build ${{ matrix.platform}}-stig
      - name: Upload build logs
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # pin@v7.0.0
        with:
          name: STIG-${{ matrix.platform}}-logs
          path: .build/*log
          include-hidden-files: true
