name: 'Tag latest and release container'
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Release to be tagged (<xxxx>.<x>)
      is_latest:
        required: true
        type: boolean
        description: Is tagging as gardenlinux:latest required
jobs:
  tag_version:
    name: tag latest and release container
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    permissions:
      packages: write
    steps:
      - name: Install python-gardenlinux-lib
        uses: gardenlinux/python-gardenlinux-lib/.github/actions/setup@9af6c50cf9ff955130dc412238ecd16f1d84d103 # pin@0.10.4
      - name: Tag manifest
        env:
          GL_CLI_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GL_CLI_REGISTRY_USERNAME: ${{ github.repository_owner }}
        run: |
          # Setup version tags for latest & release without patch
          version="${{ inputs.version }}"
          is_latest="${{ inputs.is_latest }}"

          version_major=$(echo $version | cut -d'.' -f 1)
          version_patch=$(echo $version | cut -d'.' -f 2)

          container=ghcr.io/${{ github.repository }}

          # Tag the major release version
          echo "Tagging as ${version_major}"
          gl-oci push-manifest-tags --container "${container}" --version "${version}" --tag "${version_major}"

          # Tag latest only if requested
          if [ "${is_latest}" == "true" ]; then
            echo "Tagging as latest"
            gl-oci push-manifest-tags --container "${container}" --version "${version}" --tag "latest"
          fi
