name: Tag a container as latest manually
on:
  workflow_dispatch:
    inputs: 
      version:
        required: true
        type: string
      is_latest:
        default: false
        type: boolean
        description: "Tag as gardenlinux:latest"

jobs:
  tag_container_as_latest:
    name: tag container base image as latest
    steps:
      - name: tag container as latest
        uses: ./.github/workflows/tag_latest_container.yaml
        with:
          version: ${{ inputs.version }}
          is_latest:  ${{ inputs.is_latest }}

