name: test_flavor
on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: "amd64"
      flavor:
        type: string
        required: true
      version:
        type: string
        required: true
jobs:
  test:
    name: Test flavor in chroot ${{ inputs.flavor }} (${{ inputs.arch }})
    runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    defaults:
      run:
        shell: bash
    env:
      CNAME: ''
    permissions:
      id-token: write
      actions: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # pin@v6.1.0
        with:
          path: |
            COMMIT
            VERSION
          key: build-${{ inputs.flavor }}-${{ inputs.arch }}-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Set CNAME
        run: |
          cname="$(./build --resolve-cname ${{ inputs.flavor }}-${{ inputs.arch }})"
          echo "CNAME=$cname" | tee -a "$GITHUB_ENV"
      - name: Load flavor build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # pin@v8.0.1
        with:
          name: build-${{ inputs.flavor }}-${{ inputs.arch }}
      - name: Test
        run: |
          tar -C .build -xzf $CNAME.tar.gz
          rm "$CNAME.tar.gz"

          make --directory=tests ${{ inputs.flavor }}-${{ inputs.arch }}-chroot-test
      # chroot.test.xml is written in the entrypoint tests/init
      - name: Rename test results
        if: always()
        run: mv tests/chroot.test.xml .build/$CNAME.chroot.test.xml
      - uses: pmeier/pytest-results-action@fc6576eced1f411ea48ab10e917d9cfce2960e29 # pin@v0.7.1
        if: always()
        with:
          path: ".build/${{ env.CNAME }}.chroot.test.xml"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # pin@v7.0.1
        if: always()
        with:
          if-no-files-found: ignore
          name: chroot-test-${{ env.CNAME }}
          path: |
            .build/${{ env.CNAME }}.chroot.test.log
            .build/${{ env.CNAME }}.chroot.test.xml
