name: test_flavor
on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: "amd64"
      flavor:
        type: string
        required: true
      version:
        type: string
        required: true
jobs:
  test:
    name: Test flavor in chroot ${{ inputs.flavor }} (${{ inputs.arch }})
    runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-latest-arm' || 'ubuntu-latest' }}
    defaults:
      run:
        shell: bash
    env:
      CNAME: ''
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
        with:
          submodules: true
      - uses: ./.github/actions/setup
        with:
          arch: "${{ inputs.arch }}"
      - uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # pin@v4.2.2
        with:
          path: |
            COMMIT
            VERSION
          key: build-${{ inputs.flavor }}-${{ inputs.arch }}-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Set CNAME
        run: |
          cname="$(./build --resolve-cname ${{ inputs.flavor }}-${{ inputs.arch }})"
          echo "CNAME=$cname" | tee -a "$GITHUB_ENV"
      - name: Load flavor build artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # pin@v4.1.8
        with:
          name: build-${{ inputs.flavor }}-${{ inputs.arch }}
      - name: Download test container cache
        uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # pin@v4.2.2
        with:
          path: test.oci
          key: test_container:${{ inputs.arch }}-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Prepare test environment
        run: |
          tar -C ".build/" -xzf "$CNAME.tar.gz"
          rm "$CNAME.tar.gz"

          podman load < test.oci
          rm test.oci
      - name: Test
        run: |
          make ${{ inputs.flavor }}-${{ inputs.arch }}-test
          cd ${{ github.workspace }}
      # chroot.test.xml is written in the entrypoint tests/init
      - name: Rename test results
        if: always()
        run: mv tests/chroot.test.xml .build/$CNAME.chroot.test.xml
      - uses: pmeier/pytest-results-action@fc6576eced1f411ea48ab10e917d9cfce2960e29 # pin@v0.7.1
        if: always()
        with:
          path: ".build/${{ env.CNAME }}.chroot.test.xml"
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # pin@v4.4.3
        if: always()
        with:
          if-no-files-found: ignore
          name: chroot-test-${{ env.CNAME }}
          path: |
            .build/${{ env.CNAME }}.chroot.test.log
            .build/${{ env.CNAME }}.chroot.test.xml
      - name: Pack build artifacts for upload
        run: tar -cSzvf "$CNAME.tar.gz" -C .build .
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # pin@v4.4.3
        with:
          name: build-${{ inputs.flavor }}-${{ inputs.arch }}
          overwrite: true
          path: ${{ env.CNAME }}.tar.gz
