name: test_flavor
on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: "amd64"
      flavor:
        type: string
        required: true
      version:
        type: string
        required: true
jobs:
  test:
    name: Test flavor in chroot ${{ inputs.flavor }} (${{ inputs.arch }})
    runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    defaults:
      run:
        shell: bash
    env:
      CNAME: ''
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
        with:
          submodules: true
      - uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # pin@v4.2.3
        with:
          path: |
            COMMIT
            VERSION
          key: build-${{ inputs.flavor }}-${{ inputs.arch }}-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Set CNAME
        run: |
          cname="$(./build --resolve-cname ${{ inputs.flavor }}-${{ inputs.arch }})"
          echo "CNAME=$cname" | tee -a "$GITHUB_ENV"
      - name: Load flavor build artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # pin@v4.2.1
        with:
          name: build-${{ inputs.flavor }}-${{ inputs.arch }}
      - name: Test
        run: |
          tar -C .build -xzf $CNAME.tar.gz
          rm "$CNAME.tar.gz"

          make --directory=tests ${{ inputs.flavor }}-${{ inputs.arch }}-chroot-test
      # chroot.test.xml is written in the entrypoint tests/init
      - name: Rename test results
        if: always()
        run: mv tests/chroot.test.xml .build/$CNAME.chroot.test.xml
      - uses: pmeier/pytest-results-action@fc6576eced1f411ea48ab10e917d9cfce2960e29 # pin@v0.7.1
        if: always()
        with:
          path: ".build/${{ env.CNAME }}.chroot.test.xml"
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # pin@v4.4.3
        if: always()
        with:
          if-no-files-found: ignore
          name: chroot-test-${{ env.CNAME }}
          path: |
            .build/${{ env.CNAME }}.chroot.test.log
            .build/${{ env.CNAME }}.chroot.test.xml
