name: tests
on:
  # triggered by other workflows
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      flavors_matrix:
        type: string
        required: true
    secrets:
      gcp_identity_provider:
        required: false
      gcp_service_account:
        required: false
      gcp_project_id:
        required: false
      gcp_region:
        required: false
      gcp_zone:
        required: false
      aws_role:
        required: false
      aws_session:
        required: false
      aws_region:
        required: false
      aws_s3_bucket:
        required: false
      az_client_id:
        required: false
      az_tenant_id:
        required: false
      az_subscription_id:
        required: false
      ccc_credentials:
        required: false
      tf_encryption:
        required: false
jobs:
  test_flavors:
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.flavors_matrix )}}
    uses: ./.github/workflows/test_flavor.yml
    with:
      arch: ${{ matrix.arch }}
      flavor: ${{ matrix.flavor }}
      version: ${{ inputs.version }}
