name: test_flavor
on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: "amd64"
      cname:
        type: string
        required: true
jobs:
  test:
    name: Test flavor ${{ inputs.cname }} (${{ inputs.arch }}) in QEMU
    # runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    runs-on: "ubuntu-24.04"
    if: ${{ inputs.cname != 'skip' }}
    timeout-minutes: 40
    defaults:
      run:
        shell: bash
    env:
      ABN: ""
    permissions:
      actions: write
    steps:
      - name: install qemu
        run: |
          sudo apt-get update
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends qemu-utils qemu-system-x86 qemu-system-arm swtpm socat libxml2-utils
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # pin@v6.1.0
        with:
          path: |
            COMMIT
            VERSION
          key: build-${{ inputs.cname }}-${{ inputs.arch }}-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Download test distribution
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # pin@v6.1.0
        with:
          path: tests/.build
          key: test-distribution-${{ github.run_id }}
      - name: Load certs artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # pin@v8.0.1
        with:
          name: certs
          path: cert/
      - name: Install python-gardenlinux-lib
        uses: gardenlinux/python-gardenlinux-lib/.github/actions/setup@385aaad34c414d49583c0fe3e03243d110640770 # pin@0.10.25
        with:
          version: 1.0.0-pre1
      - name: Set ABN
        run: |
          echo "ABN=$(gl-features-parse --cname ${{ inputs.cname }} --arch ${{ inputs.arch }} artifact-base-name)" | tee -a "$GITHUB_ENV"
      - name: Load flavor build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # pin@v8.0.1
        with:
          name: build-${{ inputs.cname }}-${{ inputs.arch }}
      - name: unpack build artifacts
        run: |
          mkdir ".build"
          tar -C .build -xzf $ABN.tar.gz
          rm "$ABN.tar.gz"
          tree .build
        # TODO: handle skipping better
      - name: rw for KVM
        # TODO: can we do this in a nicer way?
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Execute tests
        run: |
          if [ ! -e ".build/$ABN.raw" ]; then
            if [ -e ".build/$ABN.ova" ]; then
              echo "extracting ova"
              tar xvf ".build/$ABN.ova" -C .build
              ls -la .build
            fi
            if [ -e ".build/$ABN.vhd" ]; then
              echo "converting vhd to raw"
              qemu-img convert -f vpc -O raw ".build/$ABN.vhd" ".build/$ABN.raw"
            elif [ -e ".build/$ABN.qcow2" ]; then
              echo "converting qcow2 to raw"
              qemu-img convert -f qcow2 -O raw ".build/$ABN.qcow2" ".build/$ABN.raw"
            elif [ -e ".build/$ABN.vmdk" ]; then
              echo "converting vmdk to raw"
              qemu-img convert -f vmdk -O raw ".build/$ABN.vmdk" ".build/$ABN.raw"
            elif [ -e ".build/$ABN.gcpimage.tar.gz" ]; then
              echo "converting gcpimage to raw"
              tar -C .build -xzf ".build/$ABN.gcpimage.tar.gz"
              mv ".build/disk.raw" ".build/$ABN.raw"
            fi
          fi
          if [ -e ".build/$ABN.raw" ]; then
            ./test ".build/$ABN.raw"
          elif [ -e ".build/$ABN.pxe.tar.gz" ]; then
            ./test ".build/$ABN.pxe.tar.gz"
          elif [ -e ".build/$ABN.iso" ]; then
            ./test ".build/$ABN.iso"
          elif [ -e ".build/$ABN.oci" ]; then
            echo "skipping oci test"
            exit 0
          else
            echo "no raw, pxe or iso file, QEMU test failed"
            exit 1
          fi
      - name: Copy test results to build directory
        if: always()
        run: |
          cp tests/log/qemu.test.log .build/${ABN}.qemu.test.log || true
          cp tests/log/qemu.test.xml .build/${ABN}.qemu.test.xml || true
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # pin@v7.0.1
        if: always()
        with:
          if-no-files-found: ignore # in case test fails before writing a log
          overwrite: true # overwrite logs from previous attempt
          name: qemu-test-${{ env.ABN }}
          path: |
            .build/${{ env.ABN }}.qemu.test.log
            .build/${{ env.ABN }}.qemu.test.xml
