name: upload to S3
on:
  workflow_call:
    inputs:
      commit_id:
        type: string
        required: true
      version:
        type: string
        required: true
      flavors_matrix:
        type: string
        required: true
      run_id:
        type: string
        required: true
    secrets:
      aws_role:
        required: true
      aws_session:
        required: true
      aws_region:
        required: true
      aws_s3_bucket:
        required: true
jobs:
  upload_to_s3:
    name: upload to S3
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    env:
      CNAME: ''
    permissions:
      id-token: write
    environment: oidc_aws_s3_upload
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.flavors_matrix) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # pin@v4
        with:
          role-to-assume: ${{ secrets.aws_role }}
          role-session-name: ${{ secrets.aws_session }}
          aws-region: ${{ secrets.aws_region }}
          role-duration-seconds: 14400
      - name: Set flavor version reference
        run: |
          echo "${{ inputs.commit_id }}" | tee COMMIT
          echo "${{ inputs.version }}" | tee VERSION
      - name: Set CNAME
        run: |
          cname="$(./build --resolve-cname ${{ matrix.flavor }}-${{ matrix.arch }})"
          echo "CNAME=$cname" | tee -a "$GITHUB_ENV"
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # pin@v8.0.1
        with:
          name: build-${{ matrix.flavor }}-${{ matrix.arch }}
          github-token: ${{ github.token }}
          run-id: ${{ inputs.run_id }}
      - name: Upload to S3 bucket ${{ secrets.aws_s3_bucket }}
        run: ${{ github.workspace }}/.github/workflows/upload_to_s3.sh ${{ secrets.aws_s3_bucket }} $CNAME.tar.gz
